const $=id=>document.getElementById(id);
const fileInput=$('fileInput'),dropZone=$('dropZone'),modeSelect=$('modeSelect'),sizeSelect=$('sizeSelect'),fitSelect=$('fitSelect'),alphaThreshold=$('alphaThreshold'),alphaValue=$('alphaValue'),ditherToggle=$('ditherToggle'),convertBtn=$('convertBtn'),downloadBtn=$('downloadBtn'),statusEl=$('status'),originalCanvas=$('originalCanvas'),resultCanvas=$('resultCanvas'),originalMeta=$('originalMeta'),resultMeta=$('resultMeta'),paletteGrid=$('paletteGrid'),paletteCount=$('paletteCount'),tileCanvas=$('tileCanvas'),tileMeta=$('tileMeta'),exportMeta=$('exportMeta'),palBtn=$('palBtn'),binBtn=$('binBtn'),cBtn=$('cBtn'),hBtn=$('hBtn');
let sourceImage=null,sourceName='converted',lastResult=null;
const setStatus=(m,k='info')=>{statusEl.textContent=m;statusEl.className=`status ${k}`};
const snap=v=>Math.round(Math.max(0,Math.min(31,Math.round(v*31/255)))*255/31);
const gbaColor=c=>[snap(c[0]),snap(c[1]),snap(c[2])];
const dist=(a,b)=>(a[0]-b[0])**2+(a[1]-b[1])**2+(a[2]-b[2])**2;
function nearestIndex(rgb,palette){let bi=0,bd=Infinity;for(let i=0;i<palette.length;i++){const d=dist(rgb,palette[i]);if(d<bd){bd=d;bi=i}}return bi}
function chooseCenters(colors,k){if(colors.length<=k)return colors.slice();const c=[colors[Math.floor(colors.length/2)]],step=Math.max(1,Math.floor(colors.length/5000));while(c.length<k){let best=colors[0],score=-1;for(let n=0;n<colors.length;n+=step){let md=Infinity;for(const x of c)md=Math.min(md,dist(colors[n],x));if(md>score){score=md;best=colors[n]}}c.push(best)}return c}
function quantize(colors,k,it=7){if(!colors.length)return[];const sampled=[],step=Math.max(1,Math.ceil(colors.length/(k>32?9000:18000)));for(let i=0;i<colors.length;i+=step)sampled.push(colors[i]);let centers=chooseCenters(sampled,Math.min(k,sampled.length)).map(c=>c.slice());for(let r=0;r<it;r++){const sums=centers.map(()=>[0,0,0,0]);for(const c of sampled){let bi=0,bd=Infinity;for(let i=0;i<centers.length;i++){const d=dist(c,centers[i]);if(d<bd){bd=d;bi=i}}sums[bi][0]+=c[0];sums[bi][1]+=c[1];sums[bi][2]+=c[2];sums[bi][3]++}centers=centers.map((c,i)=>sums[i][3]?[Math.round(sums[i][0]/sums[i][3]),Math.round(sums[i][1]/sums[i][3]),Math.round(sums[i][2]/sums[i][3])]:c)}const out=[],seen=new Set();for(const c of centers.map(gbaColor)){const key=c.join(',');if(!seen.has(key)){seen.add(key);out.push(c)}}return out.slice(0,k)}
function drawSource(img){originalCanvas.width=img.naturalWidth;originalCanvas.height=img.naturalHeight;const c=originalCanvas.getContext('2d');c.imageSmoothingEnabled=false;c.clearRect(0,0,originalCanvas.width,originalCanvas.height);c.drawImage(img,0,0);originalMeta.textContent=`${img.naturalWidth}×${img.naturalHeight}`}
function getOutputSize(){const w=sourceImage.naturalWidth,h=sourceImage.naturalHeight,v=sizeSelect.value;if(v==='original')return[w,h];if(v==='auto')return[Math.ceil(w/8)*8,Math.ceil(h/8)*8];return v.split('x').map(Number)}
function preparedCanvas(){const[w,h]=getOutputSize(),c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');x.imageSmoothingEnabled=false;x.clearRect(0,0,w,h);const sw=sourceImage.naturalWidth,sh=sourceImage.naturalHeight,fit=fitSelect.value;if(sizeSelect.value==='original'){x.drawImage(sourceImage,0,0);return c}if(sizeSelect.value==='auto'){x.drawImage(sourceImage,Math.floor((w-sw)/2),Math.floor((h-sh)/2));return c}if(fit==='stretch'){x.drawImage(sourceImage,0,0,w,h);return c}const s=fit==='crop'?Math.max(w/sw,h/sh):Math.min(w/sw,h/sh),dw=Math.max(1,Math.round(sw*s)),dh=Math.max(1,Math.round(sh*s));x.drawImage(sourceImage,Math.round((w-dw)/2),Math.round((h-dh)/2),dw,dh);return c}
function renderPalette(entries,max){paletteGrid.innerHTML='';entries.slice(0,max).forEach((c,i)=>{const s=document.createElement('div');s.className='swatch'+(c===null?' transparent':'');if(c)s.style.background=`rgb(${c[0]},${c[1]},${c[2]})`;s.title=c?`Index ${i}: RGB(${c.join(', ')})`:`Index ${i}: transparent`;const l=document.createElement('span');l.className='swatch-label';l.textContent=i;s.appendChild(l);paletteGrid.appendChild(s)});paletteGrid.classList.toggle('large-palette',max>16);paletteCount.textContent=`${entries.length} / ${max}`}
function drawTilePreview(){if(!lastResult)return;const{width:w,height:h,indices}=lastResult,scale=4;tileCanvas.width=w*scale;tileCanvas.height=h*scale;const c=tileCanvas.getContext('2d');c.imageSmoothingEnabled=false;c.clearRect(0,0,tileCanvas.width,tileCanvas.height);c.drawImage(resultCanvas,0,0,tileCanvas.width,tileCanvas.height);c.strokeStyle='rgba(255,159,28,.9)';c.lineWidth=1;for(let x=0;x<=w;x+=8){c.beginPath();c.moveTo(x*scale+.5,0);c.lineTo(x*scale+.5,h*scale);c.stroke()}for(let y=0;y<=h;y+=8){c.beginPath();c.moveTo(0,y*scale+.5);c.lineTo(w*scale,y*scale+.5);c.stroke()}tileMeta.textContent=`${w/8}×${h/8} tiles • ${(w/8)*(h/8)} total`}
function convertImage(){if(!sourceImage)return;const prep=preparedCanvas(),w=prep.width,h=prep.height,threshold=+alphaThreshold.value,mode=modeSelect.value,max=mode==='8bpp'?256:16,src=prep.getContext('2d',{willReadFrequently:true}).getImageData(0,0,w,h),colors=[];let transparent=0;for(let i=0;i<src.data.length;i+=4){if(src.data[i+3]<=threshold)transparent++;else colors.push([src.data[i],src.data[i+1],src.data[i+2]])}const hasTransparency=transparent>0,visibleLimit=max-(hasTransparency?1:0),palette=quantize(colors,visibleLimit),entries=hasTransparency?[null,...palette]:palette.slice(),out=resultCanvas.getContext('2d',{willReadFrequently:true}).createImageData(w,h),indices=new Uint16Array(w*h),offset=hasTransparency?1:0;resultCanvas.width=w;resultCanvas.height=h;const work=ditherToggle.checked?new Float32Array(src.data):null;if(work)for(let i=0;i<src.data.length;i++)work[i]=src.data[i];const spread=(x,y,er,eg,eb,f)=>{if(!work||x<0||y<0||x>=w||y>=h)return;const i=(y*w+x)*4;if(src.data[i+3]<=threshold)return;work[i]+=er*f;work[i+1]+=eg*f;work[i+2]+=eb*f};for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4,p=y*w+x;if(src.data[i+3]<=threshold){out.data[i+3]=0;indices[p]=0;continue}const old=work?[Math.max(0,Math.min(255,work[i])),Math.max(0,Math.min(255,work[i+1])),Math.max(0,Math.min(255,work[i+2]))]:[src.data[i],src.data[i+1],src.data[i+2]],pi=palette.length?nearestIndex(old,palette):0,c=palette[pi]||[0,0,0];indices[p]=pi+offset;out.data[i]=c[0];out.data[i+1]=c[1];out.data[i+2]=c[2];out.data[i+3]=255;if(work){const er=old[0]-c[0],eg=old[1]-c[1],eb=old[2]-c[2];spread(x+1,y,er,eg,eb,7/16);spread(x-1,y+1,er,eg,eb,3/16);spread(x,y+1,er,eg,eb,5/16);spread(x+1,y+1,er,eg,eb,1/16)}}resultCanvas.getContext('2d').putImageData(out,0,0);renderPalette(entries,max);const aligned=w%8===0&&h%8===0;lastResult={width:w,height:h,mode,max,entries,indices,hasTransparency};resultMeta.textContent=`${w}×${h} • ${mode} • ${entries.length} colors`;downloadBtn.disabled=false;[palBtn,binBtn,cBtn,hBtn].forEach(b=>b.disabled=!aligned);exportMeta.textContent=aligned?`${(w/8)*(h/8)} tiles • ${mode}`:'Choose an 8×8-aligned size to export';drawTilePreview();setStatus(aligned?`Converted successfully. GBA binary export is ready.`:`Converted, but ${w}×${h} is not tile-aligned. Choose Auto-align or a preset before exporting.` ,aligned?'good':'warn')}
function rgb555(c){if(!c)return 0;const r=Math.round(c[0]*31/255),g=Math.round(c[1]*31/255),b=Math.round(c[2]*31/255);return r|(g<<5)|(b<<10)}
function paletteBytes(){const a=new Uint8Array(lastResult.max*2);for(let i=0;i<lastResult.max;i++){const v=rgb555(lastResult.entries[i]||null);a[i*2]=v&255;a[i*2+1]=v>>8}return a}
function tileBytes(){const{width:w,height:h,mode,indices}=lastResult,bpt=mode==='4bpp'?32:64,out=new Uint8Array((w/8)*(h/8)*bpt);let o=0;for(let ty=0;ty<h;ty+=8)for(let tx=0;tx<w;tx+=8)for(let y=0;y<8;y++){if(mode==='8bpp'){for(let x=0;x<8;x++)out[o++]=indices[(ty+y)*w+tx+x]}else{for(let x=0;x<8;x+=2){const a=indices[(ty+y)*w+tx+x]&15,b=indices[(ty+y)*w+tx+x+1]&15;out[o++]=a|(b<<4)}}}return out}
function download(data,name,type='application/octet-stream'){const blob=data instanceof Blob?data:new Blob([data],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function safeName(){return sourceName.replace(/[^a-zA-Z0-9_]/g,'_')||'asset'}
function cArray(){const n=safeName(),tb=tileBytes(),pb=paletteBytes(),hex=(v,w=2)=>'0x'+v.toString(16).toUpperCase().padStart(w,'0'),lines=(arr,per=16)=>{const x=[];for(let i=0;i<arr.length;i+=per)x.push('    '+Array.from(arr.slice(i,i+per)).map(v=>hex(v)).join(', '));return x.join(',\n')};return `#include \"${n}.h\"\n\nconst unsigned short ${n}Pal[${lastResult.max}] = {\n${(()=>{const a=[];for(let i=0;i<lastResult.max;i++)a.push(rgb555(lastResult.entries[i]||null));const x=[];for(let i=0;i<a.length;i+=8)x.push('    '+a.slice(i,i+8).map(v=>hex(v,4)).join(', '));return x.join(',\n')})()}\n};\n\nconst unsigned char ${n}Tiles[${tb.length}] = {\n${lines(tb)}\n};\n`}
function hText(){const n=safeName(),guard=`${n.toUpperCase()}_H`,tb=tileBytes();return `#ifndef ${guard}\n#define ${guard}\n\n#define ${n}Width ${lastResult.width}\n#define ${n}Height ${lastResult.height}\n#define ${n}TileCount ${(lastResult.width/8)*(lastResult.height/8)}\n#define ${n}Bpp ${lastResult.mode==='4bpp'?4:8}\n\nextern const unsigned short ${n}Pal[${lastResult.max}];\nextern const unsigned char ${n}Tiles[${tb.length}];\n\n#endif\n`}
function loadFile(file){if(!file||!file.type.startsWith('image/')){setStatus('Please choose a PNG, JPG, or WebP image.','warn');return}sourceName=file.name.replace(/\.[^.]+$/,'')||'converted';const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{sourceImage=img;drawSource(img);convertBtn.disabled=false;lastResult=null;[downloadBtn,palBtn,binBtn,cBtn,hBtn].forEach(b=>b.disabled=true);tileMeta.textContent='No tile data yet';exportMeta.textContent='Convert an image first';setStatus(`Loaded ${file.name}. Choose your GBA settings and convert.`);URL.revokeObjectURL(url)};img.onerror=()=>setStatus('That image could not be loaded.','warn');img.src=url}
fileInput.addEventListener('change',()=>loadFile(fileInput.files[0]));alphaThreshold.addEventListener('input',()=>alphaValue.textContent=alphaThreshold.value);convertBtn.addEventListener('click',convertImage);[modeSelect,sizeSelect,fitSelect,ditherToggle].forEach(x=>x.addEventListener('change',()=>sourceImage&&convertImage()));downloadBtn.addEventListener('click',()=>resultCanvas.toBlob(b=>b&&download(b,`${sourceName}_gba_${lastResult.mode}_${lastResult.width}x${lastResult.height}.png`),'image/png'));palBtn.addEventListener('click',()=>download(paletteBytes(),`${safeName()}.pal`));binBtn.addEventListener('click',()=>download(tileBytes(),`${safeName()}_${lastResult.mode}.bin`));cBtn.addEventListener('click',()=>download(cArray(),`${safeName()}.c`,'text/plain'));hBtn.addEventListener('click',()=>download(hText(),`${safeName()}.h`,'text/plain'));
['dragenter','dragover'].forEach(t=>dropZone.addEventListener(t,e=>{e.preventDefault();dropZone.classList.add('dragging')}));['dragleave','drop'].forEach(t=>dropZone.addEventListener(t,e=>{e.preventDefault();dropZone.classList.remove('dragging')}));dropZone.addEventListener('drop',e=>loadFile(e.dataTransfer.files[0]));
