const $=id=>document.getElementById(id);
const fileInput=$('fileInput'),dropZone=$('dropZone'),modeSelect=$('modeSelect'),sizeSelect=$('sizeSelect'),fitSelect=$('fitSelect'),alphaThreshold=$('alphaThreshold'),alphaValue=$('alphaValue'),ditherToggle=$('ditherToggle'),convertBtn=$('convertBtn'),downloadAllBtn=$('downloadAllBtn'),clearBtn=$('clearBtn'),statusEl=$('status'),fileCount=$('fileCount'),imageList=$('imageList'),selectionMeta=$('selectionMeta'),originalCanvas=$('originalCanvas'),resultCanvas=$('resultCanvas'),originalMeta=$('originalMeta'),resultMeta=$('resultMeta'),paletteGrid=$('paletteGrid'),paletteCount=$('paletteCount'),tileCanvas=$('tileCanvas'),tileMeta=$('tileMeta'),exportMeta=$('exportMeta'),pngBtn=$('pngBtn'),palBtn=$('palBtn'),binBtn=$('binBtn'),cBtn=$('cBtn'),hBtn=$('hBtn');
let items=[],sharedPalette=[],sharedEntries=[],selectedIndex=-1,converted=false,hasSharedTransparency=false;
const setStatus=(m,k='info')=>{statusEl.textContent=m;statusEl.className=`status ${k}`};
const snap=v=>Math.round(Math.max(0,Math.min(31,Math.round(v*31/255)))*255/31);
const gbaColor=c=>[snap(c[0]),snap(c[1]),snap(c[2])];
const dist=(a,b)=>(a[0]-b[0])**2+(a[1]-b[1])**2+(a[2]-b[2])**2;
function nearestIndex(rgb,palette){let bi=0,bd=Infinity;for(let i=0;i<palette.length;i++){const d=dist(rgb,palette[i]);if(d<bd){bd=d;bi=i}}return bi}
function chooseCenters(colors,k){if(colors.length<=k)return colors.slice();const c=[colors[Math.floor(colors.length/2)]],step=Math.max(1,Math.floor(colors.length/5000));while(c.length<k){let best=colors[0],score=-1;for(let n=0;n<colors.length;n+=step){let md=Infinity;for(const x of c)md=Math.min(md,dist(colors[n],x));if(md>score){score=md;best=colors[n]}}c.push(best)}return c}
function quantize(colors,k,it=7){if(!colors.length)return[];const sampled=[],maxSamples=k>32?12000:24000,step=Math.max(1,Math.ceil(colors.length/maxSamples));for(let i=0;i<colors.length;i+=step)sampled.push(colors[i]);let centers=chooseCenters(sampled,Math.min(k,sampled.length)).map(c=>c.slice());for(let r=0;r<it;r++){const sums=centers.map(()=>[0,0,0,0]);for(const c of sampled){let bi=0,bd=Infinity;for(let i=0;i<centers.length;i++){const d=dist(c,centers[i]);if(d<bd){bd=d;bi=i}}sums[bi][0]+=c[0];sums[bi][1]+=c[1];sums[bi][2]+=c[2];sums[bi][3]++}centers=centers.map((c,i)=>sums[i][3]?[Math.round(sums[i][0]/sums[i][3]),Math.round(sums[i][1]/sums[i][3]),Math.round(sums[i][2]/sums[i][3])]:c)}const out=[],seen=new Set();for(const c of centers.map(gbaColor)){const key=c.join(',');if(!seen.has(key)){seen.add(key);out.push(c)}}return out.slice(0,k)}
function getOutputSize(item){const w=item.img.naturalWidth,h=item.img.naturalHeight,v=sizeSelect.value;if(v==='original')return[w,h];if(v==='auto')return[Math.ceil(w/8)*8,Math.ceil(h/8)*8];return v.split('x').map(Number)}
function makePrepared(item){const[w,h]=getOutputSize(item),c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d',{willReadFrequently:true});x.imageSmoothingEnabled=false;x.clearRect(0,0,w,h);const sw=item.img.naturalWidth,sh=item.img.naturalHeight,fit=fitSelect.value;if(sizeSelect.value==='original'){x.drawImage(item.img,0,0);return c}if(sizeSelect.value==='auto'){x.drawImage(item.img,Math.floor((w-sw)/2),Math.floor((h-sh)/2));return c}if(fit==='stretch'){x.drawImage(item.img,0,0,w,h);return c}const s=fit==='crop'?Math.max(w/sw,h/sh):Math.min(w/sw,h/sh),dw=Math.max(1,Math.round(sw*s)),dh=Math.max(1,Math.round(sh*s));x.drawImage(item.img,Math.round((w-dw)/2),Math.round((h-dh)/2),dw,dh);return c}
function renderPalette(){paletteGrid.innerHTML='';const max=modeSelect.value==='8bpp'?256:16;sharedEntries.slice(0,max).forEach((c,i)=>{const s=document.createElement('div');s.className='swatch'+(c===null?' transparent':'');if(c)s.style.background=`rgb(${c[0]},${c[1]},${c[2]})`;s.title=c?`Index ${i}: RGB(${c.join(', ')})`:`Index ${i}: transparent`;const l=document.createElement('span');l.className='swatch-label';l.textContent=i;s.appendChild(l);paletteGrid.appendChild(s)});paletteGrid.classList.toggle('large-palette',max>16);paletteCount.textContent=`${sharedEntries.length} / ${max}`}
function updateList(){imageList.innerHTML='';imageList.classList.toggle('empty-state',items.length===0);if(!items.length){imageList.textContent='Upload images to create a shared palette.';fileCount.textContent='0 images loaded';return}items.forEach((item,i)=>{const row=document.createElement('button');row.className='image-row'+(i===selectedIndex?' selected':'');row.type='button';const thumb=document.createElement('canvas');thumb.width=48;thumb.height=48;const tc=thumb.getContext('2d');tc.imageSmoothingEnabled=false;const s=Math.min(48/item.img.naturalWidth,48/item.img.naturalHeight),dw=item.img.naturalWidth*s,dh=item.img.naturalHeight*s;tc.drawImage(item.img,(48-dw)/2,(48-dh)/2,dw,dh);const info=document.createElement('span');info.className='image-info';info.innerHTML=`<strong>${item.name}</strong><small>${item.img.naturalWidth}×${item.img.naturalHeight}${item.result?` → ${item.result.width}×${item.result.height}`:''}</small>`;const tag=document.createElement('span');tag.className='image-tag';tag.textContent=item.result?'READY':'SOURCE';row.append(thumb,info,tag);row.addEventListener('click',()=>selectItem(i));imageList.appendChild(row)});fileCount.textContent=`${items.length} image${items.length===1?'':'s'} loaded`}
function drawCanvasFromImage(canvas,img){canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;const c=canvas.getContext('2d');c.imageSmoothingEnabled=false;c.clearRect(0,0,canvas.width,canvas.height);c.drawImage(img,0,0)}
function selectItem(i){if(i<0||i>=items.length)return;selectedIndex=i;const item=items[i];drawCanvasFromImage(originalCanvas,item.img);originalMeta.textContent=`${item.img.naturalWidth}×${item.img.naturalHeight}`;selectionMeta.textContent=item.name;if(item.result){resultCanvas.width=item.result.width;resultCanvas.height=item.result.height;resultCanvas.getContext('2d').putImageData(item.result.imageData,0,0);resultMeta.textContent=`${item.result.width}×${item.result.height} • ${modeSelect.value}`;drawTilePreview(item);const aligned=item.result.width%8===0&&item.result.height%8===0;[pngBtn].forEach(b=>b.disabled=false);[palBtn,binBtn,cBtn,hBtn].forEach(b=>b.disabled=!aligned);exportMeta.textContent=aligned?`${item.name} • ${item.result.tileCount} tiles`:'Selected image is not tile aligned'}else{resultCanvas.width=resultCanvas.height=1;resultMeta.textContent='—';tileCanvas.width=tileCanvas.height=1;tileMeta.textContent='No tile data yet';[pngBtn,palBtn,binBtn,cBtn,hBtn].forEach(b=>b.disabled=true);exportMeta.textContent='Build the shared palette first'}updateList()}
function drawTilePreview(item){const r=item.result,scale=4;tileCanvas.width=r.width*scale;tileCanvas.height=r.height*scale;const c=tileCanvas.getContext('2d');c.imageSmoothingEnabled=false;c.putImageData(r.imageData,0,0);const temp=document.createElement('canvas');temp.width=r.width;temp.height=r.height;temp.getContext('2d').putImageData(r.imageData,0,0);c.clearRect(0,0,tileCanvas.width,tileCanvas.height);c.drawImage(temp,0,0,tileCanvas.width,tileCanvas.height);c.strokeStyle='rgba(255,159,28,.9)';for(let x=0;x<=r.width;x+=8){c.beginPath();c.moveTo(x*scale+.5,0);c.lineTo(x*scale+.5,r.height*scale);c.stroke()}for(let y=0;y<=r.height;y+=8){c.beginPath();c.moveTo(0,y*scale+.5);c.lineTo(r.width*scale,y*scale);c.stroke()}tileMeta.textContent=`${r.width/8}×${r.height/8} tiles • ${r.tileCount} total`}
function convertAll(){if(!items.length)return;const threshold=+alphaThreshold.value,max=modeSelect.value==='8bpp'?256:16,prepared=[],allColors=[];hasSharedTransparency=false;setStatus(`Analyzing ${items.length} image${items.length===1?'':'s'} for one shared palette…`);for(const item of items){const canvas=makePrepared(item),src=canvas.getContext('2d',{willReadFrequently:true}).getImageData(0,0,canvas.width,canvas.height);prepared.push({item,canvas,src});for(let i=0;i<src.data.length;i+=4){if(src.data[i+3]<=threshold)hasSharedTransparency=true;else allColors.push([src.data[i],src.data[i+1],src.data[i+2]])}}const visible=max-(hasSharedTransparency?1:0);sharedPalette=quantize(allColors,visible);sharedEntries=hasSharedTransparency?[null,...sharedPalette]:sharedPalette.slice();for(const p of prepared)mapPrepared(p.item,p.src,p.canvas.width,p.canvas.height,threshold);converted=true;renderPalette();downloadAllBtn.disabled=false;const totalTiles=items.reduce((s,x)=>s+(x.result?.tileCount||0),0);setStatus(`Shared palette ready: ${items.length} images mapped to ${sharedEntries.length}/${max} entries${totalTiles?` across ${totalTiles} tiles`:''}.`,'good');selectItem(selectedIndex<0?0:selectedIndex)}
function mapPrepared(item,src,w,h,threshold){const out=new ImageData(w,h),indices=new Uint16Array(w*h),offset=hasSharedTransparency?1:0,work=ditherToggle.checked?new Float32Array(src.data):null;if(work)for(let i=0;i<src.data.length;i++)work[i]=src.data[i];const spread=(x,y,er,eg,eb,f)=>{if(!work||x<0||y<0||x>=w||y>=h)return;const i=(y*w+x)*4;if(src.data[i+3]<=threshold)return;work[i]+=er*f;work[i+1]+=eg*f;work[i+2]+=eb*f};for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4,p=y*w+x;if(src.data[i+3]<=threshold){out.data[i+3]=0;indices[p]=0;continue}const old=work?[Math.max(0,Math.min(255,work[i])),Math.max(0,Math.min(255,work[i+1])),Math.max(0,Math.min(255,work[i+2]))]:[src.data[i],src.data[i+1],src.data[i+2]],pi=sharedPalette.length?nearestIndex(old,sharedPalette):0,c=sharedPalette[pi]||[0,0,0];indices[p]=pi+offset;out.data[i]=c[0];out.data[i+1]=c[1];out.data[i+2]=c[2];out.data[i+3]=255;if(work){const er=old[0]-c[0],eg=old[1]-c[1],eb=old[2]-c[2];spread(x+1,y,er,eg,eb,7/16);spread(x-1,y+1,er,eg,eb,3/16);spread(x,y+1,er,eg,eb,5/16);spread(x+1,y+1,er,eg,eb,1/16)}}item.result={width:w,height:h,imageData:out,indices,tileCount:(w%8===0&&h%8===0)?(w/8)*(h/8):0}}
function rgb555(c){if(!c)return 0;const r=Math.round(c[0]*31/255),g=Math.round(c[1]*31/255),b=Math.round(c[2]*31/255);return r|(g<<5)|(b<<10)}
function paletteBytes(){const max=modeSelect.value==='8bpp'?256:16,a=new Uint8Array(max*2);for(let i=0;i<max;i++){const v=rgb555(sharedEntries[i]||null);a[i*2]=v&255;a[i*2+1]=v>>8}return a}
function tileBytes(item){const r=item.result,mode=modeSelect.value,bpt=mode==='4bpp'?32:64,out=new Uint8Array((r.width/8)*(r.height/8)*bpt);let o=0;for(let ty=0;ty<r.height;ty+=8)for(let tx=0;tx<r.width;tx+=8)for(let y=0;y<8;y++){if(mode==='8bpp'){for(let x=0;x<8;x++)out[o++]=r.indices[(ty+y)*r.width+tx+x]}else{for(let x=0;x<8;x+=2){const a=r.indices[(ty+y)*r.width+tx+x]&15,b=r.indices[(ty+y)*r.width+tx+x+1]&15;out[o++]=a|(b<<4)}}}return out}
function safeName(item=items[selectedIndex]){return (item?.base||'asset').replace(/[^a-zA-Z0-9_]/g,'_')||'asset'}
function download(data,name,type='application/octet-stream'){const blob=data instanceof Blob?data:new Blob([data],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1200)}
function selected(){return selectedIndex>=0?items[selectedIndex]:null}
function cArray(item){const n=safeName(item),tb=tileBytes(item),max=modeSelect.value==='8bpp'?256:16,hex=(v,w=2)=>'0x'+v.toString(16).toUpperCase().padStart(w,'0'),byteLines=[];for(let i=0;i<tb.length;i+=16)byteLines.push('    '+Array.from(tb.slice(i,i+16)).map(v=>hex(v)).join(', '));const pals=[];for(let i=0;i<max;i++)pals.push(rgb555(sharedEntries[i]||null));const palLines=[];for(let i=0;i<pals.length;i+=8)palLines.push('    '+pals.slice(i,i+8).map(v=>hex(v,4)).join(', '));return `#include \"${n}.h\"\n\nconst unsigned short ${n}Pal[${max}] = {\n${palLines.join(',\n')}\n};\n\nconst unsigned char ${n}Tiles[${tb.length}] = {\n${byteLines.join(',\n')}\n};\n`}
function hText(item){const n=safeName(item),guard=`${n.toUpperCase()}_H`,tb=tileBytes(item),max=modeSelect.value==='8bpp'?256:16;return `#ifndef ${guard}\n#define ${guard}\n\n#define ${n}Width ${item.result.width}\n#define ${n}Height ${item.result.height}\n#define ${n}TileCount ${item.result.tileCount}\n#define ${n}Bpp ${modeSelect.value==='4bpp'?4:8}\n\nextern const unsigned short ${n}Pal[${max}];\nextern const unsigned char ${n}Tiles[${tb.length}];\n\n#endif\n`}
async function loadFiles(files){const valid=[...files].filter(f=>f.type.startsWith('image/'));if(!valid.length){setStatus('Please choose PNG, JPG, or WebP images.','warn');return}const loaded=await Promise.all(valid.map(file=>new Promise(resolve=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve({file,img,name:file.name,base:file.name.replace(/\.[^.]+$/,'')||'asset',result:null})};img.onerror=()=>{URL.revokeObjectURL(url);resolve(null)};img.src=url})));items.push(...loaded.filter(Boolean));converted=false;sharedPalette=[];sharedEntries=[];renderPalette();convertBtn.disabled=!items.length;clearBtn.disabled=!items.length;downloadAllBtn.disabled=true;updateList();if(selectedIndex<0&&items.length)selectItem(0);setStatus(`Loaded ${items.length} image${items.length===1?'':'s'}. Build one shared palette for the whole set.`)}
function clearAll(){items=[];sharedPalette=[];sharedEntries=[];selectedIndex=-1;converted=false;renderPalette();updateList();convertBtn.disabled=true;downloadAllBtn.disabled=true;clearBtn.disabled=true;[pngBtn,palBtn,binBtn,cBtn,hBtn].forEach(b=>b.disabled=true);originalCanvas.width=originalCanvas.height=resultCanvas.width=resultCanvas.height=tileCanvas.width=tileCanvas.height=1;originalMeta.textContent=resultMeta.textContent='—';selectionMeta.textContent='Nothing selected';tileMeta.textContent='No tile data yet';exportMeta.textContent='Convert images first';setStatus('Upload one or more images to begin.')}
fileInput.addEventListener('change',()=>{loadFiles(fileInput.files);fileInput.value=''});alphaThreshold.addEventListener('input',()=>alphaValue.textContent=alphaThreshold.value);convertBtn.addEventListener('click',convertAll);clearBtn.addEventListener('click',clearAll);[modeSelect,sizeSelect,fitSelect,ditherToggle].forEach(x=>x.addEventListener('change',()=>{if(items.length){converted=false;downloadAllBtn.disabled=true;items.forEach(i=>i.result=null);updateList();setStatus('Settings changed. Rebuild the shared palette to apply them to every image.','warn')}}));
pngBtn.addEventListener('click',()=>{const item=selected();if(!item?.result)return;const c=document.createElement('canvas');c.width=item.result.width;c.height=item.result.height;c.getContext('2d').putImageData(item.result.imageData,0,0);c.toBlob(b=>b&&download(b,`${safeName(item)}_gba_${modeSelect.value}.png`,'image/png'))});palBtn.addEventListener('click',()=>download(paletteBytes(),'shared_palette.pal'));binBtn.addEventListener('click',()=>{const item=selected();if(item?.result)download(tileBytes(item),`${safeName(item)}_${modeSelect.value}.bin`)});cBtn.addEventListener('click',()=>{const item=selected();if(item?.result)download(cArray(item),`${safeName(item)}.c`,'text/plain')});hBtn.addEventListener('click',()=>{const item=selected();if(item?.result)download(hText(item),`${safeName(item)}.h`,'text/plain')});downloadAllBtn.addEventListener('click',()=>{items.forEach((item,n)=>{if(!item.result)return;setTimeout(()=>{const c=document.createElement('canvas');c.width=item.result.width;c.height=item.result.height;c.getContext('2d').putImageData(item.result.imageData,0,0);c.toBlob(b=>b&&download(b,`${safeName(item)}_shared_${modeSelect.value}.png`,'image/png'))},n*150)})});
['dragenter','dragover'].forEach(t=>dropZone.addEventListener(t,e=>{e.preventDefault();dropZone.classList.add('dragging')}));['dragleave','drop'].forEach(t=>dropZone.addEventListener(t,e=>{e.preventDefault();dropZone.classList.remove('dragging')}));dropZone.addEventListener('drop',e=>loadFiles(e.dataTransfer.files));
renderPalette();updateList();
