// Build 47: shared archive extraction helper for all PixelPlayer emulator pages.
(()=>{
  const stage=document.getElementById('emuStage');if(!stage||document.getElementById('archiveTools'))return;
  const wrap=document.createElement('div');wrap.id='archiveTools';wrap.className='archive-tools';wrap.innerHTML=`<div class="archive-copy"><strong>Archive Tools</strong><small>EmulatorJS can load ZIP/7z archives directly for normal play. Use this only when you want the files physically extracted.</small></div><div class="archive-actions"><input id="archiveExtractInput" type="file" accept=".zip,application/zip" hidden><button id="archiveExtractBtn" class="secondary" type="button">Extract ZIP to Folder</button></div><div id="archiveProgressWrap" class="archive-progress-wrap" hidden><div class="archive-progress"><span id="archiveProgressBar"></span></div><div id="archiveProgressText">Ready.</div></div>`;
  const low=document.querySelector('.low-memory-bar');(low||stage).insertAdjacentElement('afterend',wrap);
  const style=document.createElement('style');style.textContent=`.archive-tools{margin:10px 0 18px;padding:11px 13px;border:1px solid var(--border2,#344039);border-radius:12px;background:rgba(12,17,14,.72);display:grid;grid-template-columns:1fr auto;gap:10px 14px;align-items:center}.archive-copy{display:flex;flex-direction:column;gap:3px}.archive-copy strong{font-size:.84rem}.archive-copy small{font-size:.7rem;line-height:1.35;color:var(--muted,#98a59c)}.archive-progress-wrap{grid-column:1/-1}.archive-progress{height:8px;border-radius:99px;background:#121713;overflow:hidden;border:1px solid var(--border2,#344039)}.archive-progress span{display:block;height:100%;width:0;background:#9be33a;transition:width .12s}.archive-progress-wrap div:last-child{font-size:.68rem;color:var(--muted,#98a59c);margin-top:5px}@media(max-width:620px){.archive-tools{grid-template-columns:1fr}.archive-actions button{width:100%}}body.rom-playing .archive-tools,body.low-memory-running .archive-tools{display:none!important}`;document.head.appendChild(style);
  const input=document.getElementById('archiveExtractInput'),btn=document.getElementById('archiveExtractBtn'),pw=document.getElementById('archiveProgressWrap'),bar=document.getElementById('archiveProgressBar'),text=document.getElementById('archiveProgressText');
  let zipPromise=null;
  function loadZipJs(){if(window.zip?.ZipReader)return Promise.resolve();if(zipPromise)return zipPromise;zipPromise=new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@zip.js/zip.js@2.7.57/dist/zip.min.js';s.onload=res;s.onerror=()=>rej(new Error('ZIP library failed to load'));document.head.appendChild(s)});return zipPromise}
  function progress(p,msg){pw.hidden=false;bar.style.width=`${Math.max(0,Math.min(100,p))}%`;text.textContent=msg}
  async function ensureDir(root,parts){let d=root;for(const part of parts.filter(Boolean))d=await d.getDirectoryHandle(part,{create:true});return d}
  async function extractToDirectory(file,root){await loadZipJs();const stem=file.name.replace(/\.zip$/i,'')||'extracted';const out=await root.getDirectoryHandle(stem,{create:true});const reader=new zip.ZipReader(new zip.BlobReader(file));const entries=await reader.getEntries();const files=entries.filter(e=>!e.directory);let done=0;for(const entry of entries){const safe=entry.filename.split('/').filter(x=>x&&x!=='.'&&x!=='..');if(!safe.length)continue;if(entry.directory){await ensureDir(out,safe);continue}const parent=await ensureDir(out,safe.slice(0,-1));const handle=await parent.getFileHandle(safe.at(-1),{create:true});const writable=await handle.createWritable();const blob=await entry.getData(new zip.BlobWriter(),{onprogress:(loaded,total)=>{const local=total?loaded/total:0;progress(((done+local)/Math.max(1,files.length))*100,`Extracting ${entry.filename}…`)}});await writable.write(blob);await writable.close();done++;progress((done/Math.max(1,files.length))*100,`Extracted ${done} of ${files.length} files…`)}await reader.close();progress(100,`Finished: ${file.name} → ${stem}/`)}
  async function fallbackDownloads(file){await loadZipJs();const reader=new zip.ZipReader(new zip.BlobReader(file));const entries=(await reader.getEntries()).filter(e=>!e.directory);let done=0;for(const entry of entries){const blob=await entry.getData(new zip.BlobWriter(),{onprogress:(loaded,total)=>{const local=total?loaded/total:0;progress(((done+local)/Math.max(1,entries.length))*100,`Preparing ${entry.filename}…`)}});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=entry.filename.split('/').pop()||'file';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000);done++;progress((done/Math.max(1,entries.length))*100,`Downloaded ${done} of ${entries.length} files…`)}await reader.close();progress(100,'Finished. Your browser downloaded the extracted files individually because folder write access is unavailable.')}
  btn.addEventListener('click',()=>input.click());
  input.addEventListener('change',async()=>{const file=input.files?.[0];input.value='';if(!file)return;btn.disabled=true;try{progress(1,'Opening archive…');if('showDirectoryPicker'in window){const root=await window.showDirectoryPicker({mode:'readwrite'});await extractToDirectory(file,root)}else await fallbackDownloads(file)}catch(e){if(e?.name==='AbortError')progress(0,'Extraction cancelled.');else{console.error(e);progress(0,`Extraction failed: ${e?.message||'unknown error'}`)}}finally{btn.disabled=false}});
})();