// Build 139: move virtual controls while preserving their native transforms.
(()=>{
  const system=document.body.dataset.system||(document.body.classList.contains('n64-page')?'n64':document.body.classList.contains('ps1-page')?'ps1':document.body.classList.contains('snes-page')?'snes':'gba');
  const LEGACY_KEY=`pixelplayer:control-layout:${system}`;
  let editing=false,drag=null,currentOrientation='';
  const nativeTransforms=new WeakMap();
  const orientation=()=>window.innerHeight>=window.innerWidth||matchMedia('(orientation: portrait)').matches?'portrait':'landscape';
  const keyFor=o=>`pixelplayer:control-layout:${system}:${o}`;
  function read(o){try{return JSON.parse(localStorage.getItem(keyFor(o))||'{}')||{}}catch{return {}}}
  function maybeMigrate(o){try{if(localStorage.getItem(keyFor(o)))return;const old=localStorage.getItem(LEGACY_KEY);if(old){localStorage.setItem(keyFor(o),old);localStorage.removeItem(LEGACY_KEY)}}catch{}}
  currentOrientation=orientation();maybeMigrate(currentOrientation);let offsets=read(currentOrientation);
  function save(reason='done'){try{localStorage.setItem(keyFor(currentOrientation),JSON.stringify(offsets))}catch{}window.dispatchEvent(new CustomEvent('pixelplayer:control-layout-saved',{detail:{system,orientation:currentOrientation,reason}}))}
  function norm(s){return (s||'').trim().toUpperCase().replace(/\s+/g,' ').replace(/[^A-Z0-9△○×□+\- ]/g,'')}
  const GROUP_SELECTOR='[class*="joystick" i],[class*="analog" i],[class*="thumbstick" i],[class*="stick" i],[class*="dpad" i]';
  function groupRoots(pad){const all=[...pad.querySelectorAll(GROUP_SELECTOR)].filter(el=>!el.classList.contains('ejs_virtualGamepad_parent'));return all.filter(el=>!all.some(other=>other!==el&&other.contains(el)))}
  function controls(){const out=[];for(const pad of document.querySelectorAll('.ejs_virtualGamepad_parent')){const groups=groupRoots(pad);groups.forEach(el=>{if(!out.includes(el))out.push(el)});for(const el of pad.querySelectorAll('.ejs_virtualGamepad_button')){if(groups.some(group=>group.contains(el)))continue;if(!out.includes(el))out.push(el)}}return out}
  function rememberNative(el){if(!nativeTransforms.has(el))nativeTransforms.set(el,el.style.getPropertyValue('transform')||'')}
  function identity(el,index){rememberNative(el);if(el.dataset.ppControlId)return el.dataset.ppControlId;const text=norm(el.textContent),cls=[...el.classList].filter(x=>/button|dpad|joystick|analog|thumbstick|stick/i.test(x)).sort().join('.');const type=/joystick|analog|thumbstick|stick/i.test(cls)?'joystick':/dpad/i.test(cls)?'dpad':text?'button':'control';let id=text&&type==='button'?`button:${text}`:`${type}:${cls||'unnamed'}`;const list=controls();const peers=list.filter(x=>x!==el&&((text&&type==='button')?norm(x.textContent)===text:[...x.classList].filter(c=>/button|dpad|joystick|analog|thumbstick|stick/i.test(c)).sort().join('.')===cls));if(peers.length)id+=`:${index}`;el.dataset.ppControlId=id;return id}
  function composedTransform(el,x=0,y=0){const base=nativeTransforms.get(el)||'';const move=`translate3d(${x}px,${y}px,0)`;return base?`${base} ${move}`:move}
  function syncOrientation(){const next=orientation();if(next===currentOrientation)return false;if(drag)end();currentOrientation=next;maybeMigrate(next);offsets=read(next);updateHint();return true}
  function clearMove(el){rememberNative(el);const base=nativeTransforms.get(el)||'';if(base)el.style.setProperty('transform',base,'important');else el.style.removeProperty('transform');el.classList.remove('pp-control-moved')}
  function apply(){syncOrientation();const list=controls();list.forEach((el,i)=>{const id=identity(el,i),p=offsets[id];el.style.removeProperty('margin-left');el.style.removeProperty('margin-top');if(p&&(p.x||p.y)){el.style.setProperty('transform',composedTransform(el,p.x||0,p.y||0),'important');el.classList.add('pp-control-moved')}else clearMove(el);el.classList.toggle('pp-control-movable',editing)})}
  function updateHint(message=''){const hint=document.getElementById('controlLayoutHint');if(!hint)return;hint.textContent=message||(editing?`Drag highlighted controls anywhere on the screen. Tap Done to save ${currentOrientation} positions.`:`Default positions are used unless moved. Portrait and landscape layouts are saved separately.`)}
  function setEditing(v){const wasEditing=editing;editing=!!v;if(wasEditing&&!editing)save('done');document.body.classList.toggle('pp-control-editing',editing);const tab=document.getElementById('moveControlsBtn'),overlay=document.getElementById('playMoveControlsBtn');if(tab){tab.classList.toggle('active-toggle',editing);tab.textContent=editing?'✓ Done Moving':'✥ Move Controls'}if(overlay){overlay.classList.toggle('active-toggle',editing);overlay.textContent=editing?'✓ Done':'✥ Move'}updateHint();apply()}
  function resetCurrent(){offsets={};save('reset');apply();updateHint(`${currentOrientation[0].toUpperCase()+currentOrientation.slice(1)} custom positions cleared; defaults restored.`)}
  function resetBoth(){try{localStorage.removeItem(keyFor('portrait'));localStorage.removeItem(keyFor('landscape'));localStorage.removeItem(LEGACY_KEY)}catch{}offsets={};save('reset-both');apply();updateHint('Portrait and landscape custom positions cleared; defaults restored.')}
  function addUI(){if(!document.getElementById('moveControlsBtn')){const host=document.querySelector('[data-panel="controller"] .controller-panel')||document.querySelector('[data-panel="controller"] .tab-card');if(host){const row=document.createElement('div');row.className='control-layout-setting';row.innerHTML='<div><strong>Virtual Control Layout</strong><span id="controlLayoutHint">Default positions are used unless moved. Portrait and landscape layouts are saved separately.</span></div><div class="control-layout-actions"><button id="moveControlsBtn" class="secondary" type="button">✥ Move Controls</button><button id="resetCurrentLayoutBtn" class="secondary" type="button">Reset This Orientation</button><button id="resetControlLayoutBtn" class="secondary" type="button">Reset Both</button></div>';host.appendChild(row);row.querySelector('#moveControlsBtn').addEventListener('click',()=>setEditing(!editing));row.querySelector('#resetCurrentLayoutBtn').addEventListener('click',resetCurrent);row.querySelector('#resetControlLayoutBtn').addEventListener('click',resetBoth)}}const overlay=document.querySelector('.play-overlay-controls');if(overlay&&!document.getElementById('playMoveControlsBtn')){const b=document.createElement('button');b.id='playMoveControlsBtn';b.className='play-control';b.type='button';b.textContent='✥ Move';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();setEditing(!editing)});const ff=document.getElementById('playFastForwardBtn');if(ff&&ff.parentElement===overlay)ff.insertAdjacentElement('afterend',b);else overlay.prepend(b)}}
  function start(e){if(!editing)return;const el=e.target.closest?.('.pp-control-movable');if(!el)return;e.preventDefault();e.stopPropagation();syncOrientation();const list=controls(),id=identity(el,list.indexOf(el)),base=offsets[id]||{x:0,y:0};drag={el,id,x0:e.clientX,y0:e.clientY,bx:base.x||0,by:base.y||0};el.classList.add('pp-control-dragging');try{el.setPointerCapture?.(e.pointerId)}catch{}}
  function move(e){if(!drag)return;e.preventDefault();e.stopPropagation();const x=Math.round(drag.bx+e.clientX-drag.x0),y=Math.round(drag.by+e.clientY-drag.y0);offsets[drag.id]={x,y};drag.el.style.removeProperty('margin-left');drag.el.style.removeProperty('margin-top');drag.el.style.setProperty('transform',composedTransform(drag.el,x,y),'important');drag.el.classList.add('pp-control-moved')}
  function end(e){if(!drag)return;e?.preventDefault?.();e?.stopPropagation?.();drag.el.classList.remove('pp-control-dragging');drag=null}
  const style=document.createElement('style');style.textContent=`.control-layout-setting{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-top:12px;padding:11px 12px;border:1px solid var(--border2,#344039);border-radius:12px;background:rgba(12,17,14,.55)}.control-layout-setting>div:first-child{display:flex;flex-direction:column;gap:3px}.control-layout-setting strong{font-size:.84rem}.control-layout-setting span{font-size:.7rem;color:var(--muted,#98a59c)}.control-layout-actions{display:flex;gap:8px;flex-wrap:wrap}.control-layout-actions button{white-space:nowrap}body.pp-control-editing .ejs_virtualGamepad_parent{pointer-events:auto!important}body.pp-control-editing .pp-control-movable{outline:2px dashed rgba(155,227,58,.95)!important;outline-offset:3px!important;cursor:move!important;touch-action:none!important;user-select:none!important;z-index:1400!important;pointer-events:auto!important;will-change:transform}body.pp-control-editing .pp-control-moved{outline-color:#f5a742!important}.pp-control-dragging{filter:brightness(1.25)!important;opacity:.9!important}#playMoveControlsBtn.active-toggle,#moveControlsBtn.active-toggle{border-color:#9be33a!important;box-shadow:0 0 0 2px rgba(155,227,58,.18)!important}@media(max-width:620px){.control-layout-setting{align-items:stretch;flex-direction:column}.control-layout-actions{display:grid;grid-template-columns:1fr 1fr}.control-layout-actions button{width:100%}.control-layout-actions button:last-child{grid-column:1/-1}}`;document.head.appendChild(style);
  document.addEventListener('pointerdown',start,true);document.addEventListener('pointermove',move,true);document.addEventListener('pointerup',end,true);document.addEventListener('pointercancel',end,true);
  const observer=new MutationObserver(()=>requestAnimationFrame(()=>{addUI();apply()}));observer.observe(document.body,{childList:true,subtree:true});
  function orientationChanged(){setTimeout(()=>{syncOrientation();apply()},120)}window.addEventListener('resize',()=>requestAnimationFrame(()=>{syncOrientation();apply()}),{passive:true});document.addEventListener('fullscreenchange',()=>setTimeout(apply,60));window.addEventListener('orientationchange',orientationChanged);
  window.PixelPlayerControlLayout={editing:()=>editing,setEditing,reset:resetCurrent,resetBoth,refresh:apply,get:()=>({...offsets}),orientation:()=>currentOrientation};addUI();apply();
})();
