// Build 76: dashboard favorites + lazy cross-system local game search.
(()=>{
  if(window.PixelPlayerDashboardLibrary76)return;window.PixelPlayerDashboardLibrary76=true;
  const search=document.getElementById('systemSearch'),systemsAnchor=document.getElementById('systems'),continueSection=document.getElementById('continueSection');if(!search||!systemsAnchor)return;
  const FAVORITES='pixelplayer:favorites:v1';
  const systems={threeDO:['3DO','3do.html'],amiga:['Amiga','amiga.html'],amstrad:['Amstrad CPC','amstrad.html'],arcade:['Arcade / FBNeo','arcade.html'],atari2600:['Atari 2600','atari.html'],atari5200:['Atari 5200','atari5200.html'],atari7800:['Atari 7800','atari7800.html'],jaguar:['Atari Jaguar','jaguar.html'],lynx:['Atari Lynx','lynx.html'],cdi:['Philips CD-i','cdi.html'],coleco:['ColecoVision','coleco.html'],commodore:['Commodore / VICE','commodore.html'],doom:['Doom / PrBoom','doom.html'],gba:['Game Boy Advance','emulator.html'],gamegear:['Game Gear','gamegear.html'],gbc:['Game Boy / Color','gbc.html'],genesis:['Genesis / Mega Drive','genesis.html'],mame:['MAME 2003','mame.html'],mastersystem:['Master System','mastersystem.html'],ngp:['Neo Geo Pocket','ngp.html'],nes:['NES / Famicom','nes.html'],n64:['Nintendo 64','n64.html'],nds:['Nintendo DS','nds.html'],ps1:['PlayStation','ps1.html'],psp:['PSP','psp.html'],sega32x:['Sega 32X','sega32x.html'],segacd:['Sega CD','segacd.html'],saturn:['Sega Saturn','saturn.html'],snes:['SNES','snes.html'],turbografx:['TurboGrafx / PC Engine','turbografx.html'],virtualboy:['Virtual Boy','virtualboy.html'],wonderswan:['WonderSwan / Color','wonderswan.html'],zx81:['ZX81','zx81.html'],zxspectrum:['ZX Spectrum','zxspectrum.html']};
  const clean=n=>(n||'Game').replace(/\.(gba|sfc|smc|fig|gd3|gd7|dx2|bsx|swc|chd|bin|cue|img|mdf|pbp|toc|cbn|m3u|ccd|z64|n64|v64|zip|7z|iso|cso|nds|nes|gb|gbc|gg|md|gen|smd|sms|32x|pce|vb|vboy|ws|wsc|ngp|ngc|a26|a52|a78|j64|jag|lnx|col|cv|d64|d71|d81|wad|iwad|pwad|tzx|tap|z80|rzx|scl|trd|p|t81|adf|adz|dms|fdi|ipf|hdf|lha)$/i,'');
  const fmt=n=>!n?'':n>=1048576?`${(n/1048576).toFixed(1)} MB`:`${Math.max(1,Math.round(n/1024))} KB`;
  const getFavs=()=>{try{return JSON.parse(localStorage.getItem(FAVORITES)||'[]')}catch{return[]}};
  const style=document.createElement('style');style.textContent=`
  .dash-favorites,.dash-game-results{margin-top:18px;border:1px solid #253027;background:linear-gradient(145deg,#0f1511,#0a0e0b);border-radius:20px;padding:14px}.dash-favorites[hidden],.dash-game-results[hidden]{display:none!important}.dash-mini-head{display:flex;align-items:end;justify-content:space-between;gap:10px;margin-bottom:10px}.dash-mini-head h2{margin:0;font-size:1.02rem}.dash-mini-head span{color:#7f8b80;font-size:.7rem}.dash-fav-list,.dash-result-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(225px,1fr));gap:8px}.dash-game-card{display:grid;grid-template-columns:42px 1fr auto;gap:9px;align-items:center;text-decoration:none;color:#eef4ee;border:1px solid #29342b;border-radius:13px;background:#111713;padding:9px;transition:transform .17s ease,border-color .17s ease,background .17s ease}.dash-game-card:hover,.dash-game-card:active{transform:translateY(-2px);border-color:#5e8b3e;background:#151d16}.dash-game-icon{width:42px;height:42px;border-radius:10px;background:#e9eee9;display:grid;place-items:center;overflow:hidden}.dash-game-icon .system-art-img{max-width:35px;max-height:35px}.dash-game-copy{min-width:0;display:grid;gap:2px}.dash-game-copy strong{font-size:.78rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dash-game-copy span{font-size:.6rem;color:#9adf5c;font-weight:900;text-transform:uppercase;letter-spacing:.06em}.dash-game-copy small{font-size:.6rem;color:#7f8b80;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dash-game-open{font-size:.62rem;color:#91d957;font-weight:900}.dash-search-status{padding:13px;border:1px dashed #2c372e;border-radius:12px;color:#859188;font-size:.75rem;text-align:center}.dashboard-search.searching-games{border-color:#6db735;box-shadow:0 0 0 3px rgba(111,185,53,.1)}@media(max-width:620px){.dash-fav-list,.dash-result-list{grid-template-columns:1fr}.dash-favorites,.dash-game-results{padding:12px}}
  body.dashboard-playing .dash-game-card{transition:none!important}
  @media(prefers-reduced-motion:reduce){.dash-game-card{transition:none!important}}
  `;document.head.appendChild(style);
  const favSection=document.createElement('section');favSection.className='dash-favorites';favSection.innerHTML='<div class="dash-mini-head"><h2>★ Favorites</h2><span class="dash-fav-meta"></span></div><div class="dash-fav-list"></div>';continueSection?.insertAdjacentElement('afterend',favSection);
  const resultSection=document.createElement('section');resultSection.className='dash-game-results';resultSection.hidden=true;resultSection.innerHTML='<div class="dash-mini-head"><h2>Game Results</h2><span class="dash-result-meta"></span></div><div class="dash-result-list"></div>';systemsAnchor.insertAdjacentElement('afterend',resultSection);
  function card(rec){const s=systems[rec.system];if(!s)return null;const a=document.createElement('a');a.className='dash-game-card';a.href=`${s[1]}?build=76&find=${encodeURIComponent(rec.name)}`;const icon=window.PixelPlayerSystemIcon?.forHref?.(s[1])||'';a.innerHTML=`<div class="dash-game-icon system-icon-art">${icon}</div><div class="dash-game-copy"><span>${s[0]}</span><strong></strong><small>${rec.path||rec.name}${rec.size?` · ${fmt(rec.size)}`:''}</small></div><span class="dash-game-open">OPEN →</span>`;a.querySelector('strong').textContent=clean(rec.name);window.PixelPlayerSystemIcon?.hydrate?.(a);return a}
  function renderFavorites(){const list=favSection.querySelector('.dash-fav-list'),meta=favSection.querySelector('.dash-fav-meta'),rows=getFavs().filter(x=>systems[x.system]);list.innerHTML='';favSection.hidden=!rows.length;if(!rows.length)return;meta.textContent=`${rows.length} saved`;for(const r of rows.slice(0,24)){const a=card(r);if(a)list.appendChild(a)}}renderFavorites();window.addEventListener('storage',e=>{if(e.key===FAVORITES)renderFavorites()});
  function openDb(name,version=1){return new Promise((res,rej)=>{const r=indexedDB.open(name,version);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);r.onupgradeneeded=()=>{try{r.transaction.abort()}catch{}}})}
  async function cursorMeta(dbName,store,filter,map,version=1){const out=[];try{const db=await openDb(dbName,version);if(!db.objectStoreNames.contains(store)){db.close();return out}await new Promise((res,rej)=>{const req=db.transaction(store,'readonly').objectStore(store).openCursor();req.onsuccess=()=>{const c=req.result;if(!c){res();return}const v=c.value;if(!filter||filter(v)){const m=map(v);if(m)out.push(m)}c.continue()};req.onerror=()=>rej(req.error)});db.close()}catch{}return out}
  let indexPromise=null,gameIndex=[];
  async function buildIndex(){if(indexPromise)return indexPromise;indexPromise=(async()=>{const sets=await Promise.all([
    cursorMeta('PixelPlayerExpanded','games',v=>v?.source==='library'&&v.system,v=>({system:v.system,name:v.name,size:v.size||0,path:v.path||v.name})),
    cursorMeta('PixelPlayerLibrary','roms',null,v=>({system:'gba',name:v.name,size:v.size||0,path:v.path||v.name})),
    cursorMeta('PixelPlayerSnesLibrary','roms',null,v=>({system:'snes',name:v.name,size:v.size||0,path:v.path||v.name})),
    cursorMeta('PixelPlayerN64Library','games',null,v=>({system:'n64',name:v.name,size:v.size||0,path:v.path||v.name})),
    cursorMeta('PixelPlayerPs1Library','games',null,v=>({system:'ps1',name:v.name,size:v.size||0,path:v.path||v.name}))
  ]);const seen=new Set();gameIndex=[];for(const arr of sets)for(const r of arr){if(!r?.name||!systems[r.system])continue;const k=`${r.system}::${r.name}`;if(seen.has(k))continue;seen.add(k);gameIndex.push(r)}gameIndex.sort((a,b)=>clean(a.name).localeCompare(clean(b.name)));return gameIndex})();return indexPromise}
  let token=0;
  async function searchGames(q){const my=++token;if(!q){resultSection.hidden=true;search.classList.remove('searching-games');return}resultSection.hidden=false;search.classList.add('searching-games');const list=resultSection.querySelector('.dash-result-list'),meta=resultSection.querySelector('.dash-result-meta');list.innerHTML='<div class="dash-search-status">Searching your local game libraries…</div>';meta.textContent='';const idx=await buildIndex();if(my!==token)return;const terms=q.toLowerCase().split(/\s+/).filter(Boolean),hits=idx.filter(r=>{const h=`${clean(r.name)} ${r.path||''} ${systems[r.system]?.[0]||''}`.toLowerCase();return terms.every(t=>h.includes(t))}).slice(0,60);list.innerHTML='';meta.textContent=`${hits.length}${hits.length===60?'+' :''} found`;if(!hits.length){list.innerHTML='<div class="dash-search-status">No indexed games match that search.</div>';return}for(const r of hits){const a=card(r);if(a)list.appendChild(a)}}
  let debounce=null;search.addEventListener('input',()=>{clearTimeout(debounce);const q=search.value.trim();debounce=setTimeout(()=>searchGames(q),120)});if(search.value.trim())searchGames(search.value.trim());
})();