// Build 76: performance-safe emulator UX layer: loading, favorites, details, metadata and transitions.
(()=>{
  if(window.PixelPlayerUx76)return;window.PixelPlayerUx76=true;
  const body=document.body,stage=document.getElementById('emuStage');if(!stage)return;
  const system=body.dataset.system||(body.classList.contains('n64-page')?'n64':body.classList.contains('ps1-page')?'ps1':body.classList.contains('snes-page')?'snes':'gba');
  const label=body.dataset.label||({gba:'Game Boy Advance',snes:'SNES',ps1:'PlayStation',n64:'Nintendo 64'}[system]||system.toUpperCase());
  const FAVORITES='pixelplayer:favorites:v1',STATS='pixelplayer:game-stats:v1';let pending=null,readyCounted=false,loadingObserver=null,libraryObserver=null;
  const clean=n=>(n||'Game').replace(/\.(gba|sfc|smc|fig|gd3|gd7|dx2|bsx|swc|chd|bin|cue|img|mdf|pbp|toc|cbn|m3u|ccd|z64|n64|v64|zip|7z|iso|cso|nds|nes|gb|gbc|gg|md|gen|smd|sms|32x|pce|vb|vboy|ws|wsc|ngp|ngc|a26|a52|a78|j64|jag|lnx|col|cv|d64|d71|d81|wad|iwad|pwad|tzx|tap|z80|rzx|scl|trd|p|t81|adf|adz|dms|fdi|ipf|hdf|lha)$/i,'');
  const fmt=n=>!n?'Unknown':n>=1048576?`${(n/1048576).toFixed(2)} MB`:`${Math.max(1,Math.round(n/1024))} KB`;
  const getJson=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}};
  const setJson=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
  const gameKey=n=>`${system}::${n||'Game'}`;
  function motionOff(){return body.classList.contains('rom-playing')||body.classList.contains('low-memory-running')||body.classList.contains('ui-motion-off')}

  const style=document.createElement('style');style.textContent=`
  body:not(.rom-playing):not(.low-memory-running):not(.ui-motion-off) .tab-card,body:not(.rom-playing):not(.low-memory-running):not(.ui-motion-off) .rom-library-row,body:not(.rom-playing):not(.low-memory-running):not(.ui-motion-off) .rom-library-item,body:not(.rom-playing):not(.low-memory-running):not(.ui-motion-off) .recent-rom-item{transition:transform .18s ease,border-color .18s ease,opacity .18s ease,background .18s ease}
  body:not(.rom-playing):not(.low-memory-running):not(.ui-motion-off) .rom-library-row:active,body:not(.rom-playing):not(.low-memory-running):not(.ui-motion-off) .rom-library-item:active,body:not(.rom-playing):not(.low-memory-running):not(.ui-motion-off) .recent-rom-item:active{transform:scale(.992)}
  body:not(.rom-playing):not(.low-memory-running):not(.ui-motion-off) button:active{transform:scale(.975)}
  .pp-load{position:fixed;inset:0;z-index:9999;display:grid;place-items:center;background:#050706;opacity:0;pointer-events:none;transition:opacity .18s ease}.pp-load.show{opacity:1;pointer-events:auto}.pp-load-card{width:min(420px,calc(100% - 34px));padding:24px;border:1px solid #2b382d;border-radius:22px;background:linear-gradient(145deg,#111813,#090d0a);box-shadow:0 28px 80px rgba(0,0,0,.55)}.pp-load-logo{display:flex;align-items:center;gap:12px;margin-bottom:20px}.pp-load-mark{width:42px;height:42px;border:2px solid #8fdf4d;border-radius:12px;display:grid;place-items:center;color:#a9ed69;font-weight:950;box-shadow:0 0 0 5px rgba(143,223,77,.07)}.pp-load-logo strong{font-size:1.18rem}.pp-load-logo small{display:block;color:#7f8c81;font-size:.7rem;margin-top:2px}.pp-load-file{font-size:.82rem;color:#dce7dd;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-bottom:12px}.pp-load-track{height:8px;border:1px solid #29352b;border-radius:99px;background:#0b100c;overflow:hidden}.pp-load-fill{display:block;height:100%;width:0;background:linear-gradient(90deg,#75c63d,#b0ef6e);transition:width .22s ease}.pp-load-status{display:flex;justify-content:space-between;gap:10px;margin-top:9px;color:#8d9a8f;font-size:.72rem}.pp-load-status strong{color:#a5e767}.pp-load-steps{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;margin-top:17px}.pp-load-step{font-size:.59rem;color:#5f6b61;text-align:center}.pp-load-step.done,.pp-load-step.active{color:#9bdf60}.pp-load-step.active{font-weight:900}
  body:not(.rom-playing):not(.low-memory-running):not(.ui-motion-off) .pp-load.show .pp-load-mark{animation:ppPulse 1.05s ease-in-out infinite}@keyframes ppPulse{50%{transform:scale(1.06);box-shadow:0 0 0 9px rgba(143,223,77,.04)}}
  body.rom-playing .pp-load-mark,body.low-memory-running .pp-load-mark,body.ui-motion-off .pp-load-mark{animation:none!important}.pp-fav{margin-left:auto;flex:0 0 auto;width:34px;height:34px;padding:0!important;display:grid!important;place-items:center;border-radius:10px!important;font-size:1.05rem!important;background:#111812!important;color:#677269!important;border:1px solid #2a352c!important}.pp-fav.on{color:#ffd75d!important;border-color:#75652f!important;background:#1b180d!important}.pp-detail-trigger{cursor:pointer}.pp-detail{position:fixed;inset:0;z-index:9998;display:none;place-items:center;padding:18px;background:rgba(2,4,3,.78);backdrop-filter:blur(5px)}.pp-detail.open{display:grid}.pp-detail-card{width:min(430px,100%);border:1px solid #2b382d;border-radius:20px;background:#0e140f;padding:18px;box-shadow:0 24px 70px rgba(0,0,0,.55)}.pp-detail-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.pp-detail-head h3{margin:3px 0 0;font-size:1.05rem}.pp-detail-head small{color:#8fdf4d;font-size:.65rem;font-weight:900;text-transform:uppercase;letter-spacing:.08em}.pp-detail-close{padding:7px 10px!important}.pp-detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:15px 0}.pp-detail-grid div{padding:10px;border:1px solid #263128;border-radius:11px;background:#0a0f0b}.pp-detail-grid span{display:block;color:#718075;font-size:.62rem;margin-bottom:3px}.pp-detail-grid strong{font-size:.76rem;word-break:break-word}.pp-detail-actions{display:flex;gap:8px}.pp-detail-actions button{flex:1}.play-transition-shade{position:fixed;inset:0;background:#000;z-index:9997;pointer-events:none;opacity:0;transition:opacity .18s ease}body.pp-transition-in .play-transition-shade,body.pp-transition-out .play-transition-shade{opacity:1}body.rom-playing #game{animation:none}body:not(.ui-motion-off).pp-reveal #game{animation:ppReveal .2s ease both}@keyframes ppReveal{from{opacity:0;transform:scale(.992)}to{opacity:1;transform:none}}
  @media(prefers-reduced-motion:reduce){.pp-load,.pp-load-fill,.play-transition-shade{transition:none!important}.pp-load-mark,#game{animation:none!important}}
  `;document.head.appendChild(style);

  const load=document.createElement('div');load.className='pp-load';load.innerHTML=`<div class="pp-load-card"><div class="pp-load-logo"><div class="pp-load-mark">PP</div><div><strong>PixelPlayer</strong><small>Preparing your game</small></div></div><div class="pp-load-file">Waiting for ROM…</div><div class="pp-load-track"><span class="pp-load-fill"></span></div><div class="pp-load-status"><span>Reading ROM</span><strong>0%</strong></div><div class="pp-load-steps"><span class="pp-load-step">Reading ROM</span><span class="pp-load-step">Preparing core</span><span class="pp-load-step">Loading emulator</span><span class="pp-load-step">Starting game</span></div></div>`;document.body.appendChild(load);
  const shade=document.createElement('div');shade.className='play-transition-shade';document.body.appendChild(shade);
  const detail=document.createElement('div');detail.className='pp-detail';detail.innerHTML=`<div class="pp-detail-card"><div class="pp-detail-head"><div><small class="pp-detail-system"></small><h3 class="pp-detail-name"></h3></div><button class="secondary pp-detail-close">Close</button></div><div class="pp-detail-grid"><div><span>File size</span><strong class="pp-detail-size">—</strong></div><div><span>Play count</span><strong class="pp-detail-plays">0</strong></div><div><span>Last played</span><strong class="pp-detail-last">Never</strong></div><div><span>Last save state</span><strong class="pp-detail-save">None</strong></div></div><div class="pp-detail-actions"><button class="secondary pp-detail-fav">☆ Favorite</button><button class="primary pp-detail-play">Play</button></div></div>`;document.body.appendChild(detail);

  function phase(i,text,pct){const steps=[...load.querySelectorAll('.pp-load-step')];steps.forEach((x,n)=>{x.classList.toggle('done',n<i);x.classList.toggle('active',n===i)});load.querySelector('.pp-load-fill').style.width=`${pct}%`;load.querySelector('.pp-load-status span').textContent=text;load.querySelector('.pp-load-status strong').textContent=`${pct}%`}
  function showLoading(name,size){pending={name:name||'Game',size:size||0};readyCounted=false;load.querySelector('.pp-load-file').textContent=`${name||'Game'}${size?` · ${fmt(size)}`:''}`;load.classList.add('show');phase(0,'Reading ROM',8);requestAnimationFrame(()=>phase(1,'Preparing core',28));startLoaderWatch()}
  function startLoaderWatch(){loadingObserver?.disconnect();loadingObserver=new MutationObserver(muts=>{for(const m of muts)for(const n of m.addedNodes||[])if(n?.tagName==='SCRIPT'&&/loader\.js/i.test(n.src||'')){phase(2,'Loading emulator',62);return}});loadingObserver.observe(document.documentElement,{childList:true,subtree:true})}
  function finishLoading(){if(!load.classList.contains('show'))return;phase(3,'Starting game',92);setTimeout(()=>{phase(3,'Starting game',100);setTimeout(()=>load.classList.remove('show'),130)},90);loadingObserver?.disconnect();loadingObserver=null}
  document.addEventListener('change',e=>{if(e.target?.id==='romInput'&&e.target.files?.[0]){const f=e.target.files[0];showLoading(f.name,f.size)}},true);
  document.addEventListener('drop',e=>{if(e.target?.closest?.('#romDrop')&&e.dataTransfer?.files?.[0]){const f=e.dataTransfer.files[0];showLoading(f.name,f.size)}},true);
  document.addEventListener('click',e=>{const b=e.target.closest?.('.rom-library-row .primary,.rom-library-item .primary,.recent-rom-item .play');if(!b)return;const row=b.closest('.rom-library-row,.rom-library-item,.recent-rom-item'),name=row?.querySelector('strong')?.textContent?.trim()||'Game',meta=row?.querySelector('.rom-library-info span,small,span')?.textContent||'';const m=meta.match(/([\d.]+)\s*(KB|MB|GB)/i);let size=0;if(m){size=parseFloat(m[1])*(m[2].toUpperCase()==='GB'?1073741824:m[2].toUpperCase()==='MB'?1048576:1024)}showLoading(name,size);pending={name,size}},true);
  window.addEventListener('pixelplayer:rom-start',()=>{if(load.classList.contains('show'))phase(2,'Loading emulator',58)});

  function favs(){return getJson(FAVORITES,[])}function isFav(n){return favs().some(x=>x.key===gameKey(n))}function toggleFav(rec){let a=favs(),i=a.findIndex(x=>x.key===gameKey(rec.name));if(i>=0)a.splice(i,1);else a.unshift({key:gameKey(rec.name),system,label,name:rec.name,size:rec.size||0,path:rec.path||'',href:location.pathname.split('/').pop()||'',addedAt:Date.now()});setJson(FAVORITES,a.slice(0,300));window.dispatchEvent(new CustomEvent('pixelplayer:favorites-changed'));return i<0}
  function statsFor(n){return getJson(STATS,{})[gameKey(n)]||{playCount:0,lastPlayed:0,lastSaveAt:0}}
  function updateStats(name,patch){const all=getJson(STATS,{}),k=gameKey(name),old=all[k]||{playCount:0,lastPlayed:0,lastSaveAt:0};all[k]={...old,...patch};setJson(STATS,all)}
  function rowRecord(row){const name=row.querySelector('strong')?.textContent?.trim()||'Game',meta=row.querySelector('.rom-library-info span')?.textContent||'',path=meta.split(' • ')[0]||name,m=meta.match(/([\d.]+)\s*(KB|MB|GB)/i);let size=0;if(m)size=parseFloat(m[1])*(m[2].toUpperCase()==='GB'?1073741824:m[2].toUpperCase()==='MB'?1048576:1024);return{name,size,path,row}}
  function openDetails(rec){const s=statsFor(rec.name);detail.querySelector('.pp-detail-system').textContent=label;detail.querySelector('.pp-detail-name').textContent=clean(rec.name);detail.querySelector('.pp-detail-size').textContent=fmt(rec.size);detail.querySelector('.pp-detail-plays').textContent=String(s.playCount||0);detail.querySelector('.pp-detail-last').textContent=s.lastPlayed?new Date(s.lastPlayed).toLocaleString():'Never';detail.querySelector('.pp-detail-save').textContent=s.lastSaveAt?new Date(s.lastSaveAt).toLocaleString():'None';const f=detail.querySelector('.pp-detail-fav');f.textContent=isFav(rec.name)?'★ Favorited':'☆ Favorite';f.onclick=()=>{const on=toggleFav(rec);f.textContent=on?'★ Favorited':'☆ Favorite';enhanceRows()};detail.querySelector('.pp-detail-play').onclick=()=>{detail.classList.remove('open');const p=rec.row?.querySelector('.primary,.play');p?.click()};detail.classList.add('open')}
  detail.querySelector('.pp-detail-close').onclick=()=>detail.classList.remove('open');detail.addEventListener('click',e=>{if(e.target===detail)detail.classList.remove('open')});
  function enhanceRows(){if(motionOff())return;for(const row of document.querySelectorAll('.rom-library-row,.rom-library-item')){if(row.dataset.ppEnhanced==='1'){const rec=rowRecord(row),b=row.querySelector('.pp-fav');if(b){b.classList.toggle('on',isFav(rec.name));b.textContent=isFav(rec.name)?'★':'☆'}continue}row.dataset.ppEnhanced='1';row.classList.add('pp-detail-trigger');const rec=rowRecord(row),b=document.createElement('button');b.type='button';b.className='pp-fav';b.title='Favorite';b.textContent=isFav(rec.name)?'★':'☆';b.classList.toggle('on',isFav(rec.name));b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const on=toggleFav(rec);b.textContent=on?'★':'☆';b.classList.toggle('on',on)});row.appendChild(b);row.addEventListener('click',e=>{if(e.target.closest('button,a,input,label'))return;openDetails(rowRecord(row))})}}
  libraryObserver=new MutationObserver(enhanceRows);const lib=document.getElementById('romLibraryList');if(lib)libraryObserver.observe(lib,{childList:true,subtree:true});enhanceRows();
  window.addEventListener('pixelplayer:low-memory-changed',e=>{body.classList.toggle('ui-motion-off',!!e.detail?.enabled);if(e.detail?.running)libraryObserver?.disconnect();else if(lib)libraryObserver?.observe(lib,{childList:true,subtree:true})});
  window.addEventListener('pixelplayer:manual-state-saved',()=>{const n=pending?.name||document.getElementById('sessionRom')?.textContent||'Game';updateStats(n,{lastSaveAt:Date.now()})});
  const readyObserver=new MutationObserver(()=>{if(!stage.classList.contains('ready'))return;finishLoading();if(!readyCounted){readyCounted=true;const n=pending?.name||document.getElementById('romName')?.textContent?.split(' • ')[0]||document.getElementById('sessionRom')?.textContent||'Game',s=statsFor(n);updateStats(n,{playCount:(s.playCount||0)+1,lastPlayed:Date.now()})}});readyObserver.observe(stage,{attributes:true,attributeFilter:['class']});
  const find=new URLSearchParams(location.search).get('find');if(find){const input=document.getElementById('romLibrarySearch');if(input){input.value=clean(find);input.dispatchEvent(new Event('input',{bubbles:true}));setTimeout(()=>{const row=[...document.querySelectorAll('.rom-library-row,.rom-library-item')].find(r=>clean(r.querySelector('strong')?.textContent||'').toLowerCase()===clean(find).toLowerCase());if(row){row.scrollIntoView({block:'center'});openDetails(rowRecord(row))}},220)}}
  document.addEventListener('click',e=>{if(!e.target.closest?.('#playExitBtn'))return;e.preventDefault();e.stopImmediatePropagation();body.classList.add('pp-transition-out');setTimeout(()=>{body.classList.remove('rom-playing');window.dispatchEvent(new Event('resize'));setTimeout(()=>body.classList.remove('pp-transition-out'),60)},150)},true);
})();