// Build 94: shared game-cover resolver with cached box art and system-art fallback.
(()=>{
  if(window.PixelPlayerGameArt94)return;window.PixelPlayerGameArt94=true;
  const DB='PixelPlayerBoxArt',STORE='images';
  const hrefs={threeDO:'3do.html',amiga:'amiga.html',amstrad:'amstrad.html',arcade:'arcade.html',atari2600:'atari.html',atari5200:'atari5200.html',atari7800:'atari7800.html',jaguar:'jaguar.html',lynx:'lynx.html',cdi:'cdi.html',coleco:'coleco.html',commodore:'commodore.html',doom:'doom.html',gba:'emulator.html',gamegear:'gamegear.html',gbc:'gbc.html',genesis:'genesis.html',mame:'mame.html',mastersystem:'mastersystem.html',ngp:'ngp.html',nes:'nes.html',n64:'n64.html',nds:'nds.html',ps1:'ps1.html',psp:'psp.html',sega32x:'sega32x.html',segacd:'segacd.html',saturn:'saturn.html',snes:'snes.html',turbografx:'turbografx.html',virtualboy:'virtualboy.html',wonderswan:'wonderswan.html',zx81:'zx81.html',zxspectrum:'zxspectrum.html'};
  const clean=n=>(n||'Game').replace(/\.(gba|sfc|smc|fig|gd3|gd7|dx2|bsx|swc|chd|bin|cue|img|mdf|pbp|toc|cbn|m3u|ccd|z64|n64|v64|zip|7z|iso|cso|nds|nes|fds|unf|unif|gb|gbc|gg|md|gen|smd|sms|32x|pce|vb|vboy|ws|wsc|ngp|ngc|a26|a52|a78|j64|jag|lnx|col|cv|d64|d71|d81|wad|iwad|pwad|tzx|tap|z80|rzx|scl|trd|p|t81|adf|adz|dms|fdi|ipf|hdf|lha)$/i,'');
  function mapFor(system){try{return JSON.parse(localStorage.getItem(`pixelplayer:boxart-map:${system}`)||'{}')}catch{return{}}}
  function recFor(system,name){const m=mapFor(system),title=clean(name);return m[title]||m[name]||null}
  function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,2);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'key'});if(!d.objectStoreNames.contains('catalogs'))d.createObjectStore('catalogs',{keyPath:'key'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
  async function cachedBlob(system,name){try{const d=await openDb(),title=clean(name),row=await new Promise((res,rej)=>{const q=d.transaction(STORE,'readonly').objectStore(STORE).get(`${system}::${title}`);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error)});d.close();return row?.blob||null}catch{return null}}
  function systemFallback(host,system,href){host.classList.add('pp-game-art-host');host.classList.remove('has-game-art');host.querySelectorAll('.pp-game-cover-art').forEach(x=>x.remove());const slot=host.querySelector('.pp-game-system-fallback')||document.createElement('div');slot.className='pp-game-system-fallback system-icon-art';slot.innerHTML=window.PixelPlayerSystemIcon?.forHref?.(href||hrefs[system]||'')||`<span class="pp-game-system-code">${String(system||'PP').toUpperCase()}</span>`;if(!slot.isConnected)host.appendChild(slot);window.PixelPlayerSystemIcon?.hydrate?.(slot);return slot}
  async function fill(host,{system,name,href}={}){if(!host||!system)return false;const fallback=systemFallback(host,system,href);const rec=recFor(system,name),url=typeof rec==='string'?rec:rec?.url;if(!url)return false;let src=url,obj=null;const blob=await cachedBlob(system,name);if(blob){obj=URL.createObjectURL(blob);src=obj}return new Promise(resolve=>{const img=document.createElement('img');img.className='pp-game-cover-art';img.alt='';img.decoding='async';img.loading='lazy';img.onload=()=>{host.classList.add('has-game-art');fallback.hidden=true;if(obj)setTimeout(()=>URL.revokeObjectURL(obj),0);resolve(true)};img.onerror=()=>{img.remove();fallback.hidden=false;if(obj)URL.revokeObjectURL(obj);resolve(false)};img.src=src;host.appendChild(img)})}
  const style=document.createElement('style');style.textContent='.pp-game-art-host{position:relative;overflow:hidden}.pp-game-system-fallback{position:absolute;inset:0;display:grid;place-items:center;padding:8%;background:#e9eee9}.pp-game-system-fallback .system-logo-img{max-width:88%;max-height:88%;object-fit:contain}.pp-game-system-fallback .system-fallback,.pp-game-system-fallback .system-svg{width:88%;height:88%}.pp-game-system-code{font:900 12px/1 ui-monospace,monospace;color:#1d281f}.pp-game-cover-art{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;object-fit:fill!important;margin:0!important;max-width:none!important;max-height:none!important;z-index:2}.has-game-art>.pp-game-system-fallback{display:none!important}';document.head.appendChild(style);
  window.PixelPlayerGameArt={fill,systemFallback,clean,hrefFor:system=>hrefs[system]||''};
})();