// Build 61: N64 runtime with native 320x240 rendering and event-driven controller status.
(()=>{
const $=id=>document.getElementById(id),input=$('romInput'),drop=$('romDrop'),name=$('romName'),stage=$('emuStage'),status=$('emuStatus'),session=$('sessionRom'),control=$('controlStatus');
const EXT=/\.(z64|n64|v64|zip|7z)$/i;let started=false,ready=false,paused=false,ff=false,url=null,current='game';
const buttons=['pauseBtn','fastForwardBtn','resetBtn','fullscreenBtn','screenshotBtn','exportSaveBtn'].map($);
function emu(){return window.EJS_emulator||null} function stat(t){if(status)status.textContent=t} function cstat(t,k='info'){if(control){control.textContent=t;control.className=`status ${k}`}}
function enable(v){buttons.forEach(b=>{if(b)b.disabled=!v});$('controlCenter')?.classList.toggle('disabled-panel',!v);if($('saveInput'))$('saveInput').disabled=!v;$('importSaveLabel')?.classList.toggle('disabled',!v)}
function clean(s){return(s||'game').replace(EXT,'').replace(/[^a-z0-9_\- ]/gi,'_').trim()||'game'}
async function wait(){for(let i=0;i<150;i++){const e=emu();if(e?.gameManager?.FS)return e;await new Promise(r=>setTimeout(r,100))}return null}
function download(data,file,type='application/octet-stream'){const b=new Blob([data],{type}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=file;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function startRom(file){if(!file||!EXT.test(file.name||'')){stat('Choose a supported N64 ROM (.z64, .n64, .v64), ZIP archive, or 7z archive.');return}if(started){location.reload();return}started=true;url=URL.createObjectURL(file);current=clean(file.name);name.textContent=`${file.name} • ${(file.size/1048576).toFixed(2)} MB`;session.textContent=current;stage.classList.add('ready');stat('Loading Nintendo 64 core…');cstat('Starting Mupen64Plus-Next…');window.dispatchEvent(new CustomEvent('pixelplayer:rom-start',{detail:{system:'n64'}}));
window.EJS_player='#game';window.EJS_core='n64';window.EJS_gameUrl=url;window.EJS_gameName=current;window.EJS_pathtodata='https://cdn.emulatorjs.org/stable/data/';window.EJS_startOnLoaded=true;window.EJS_askBeforeExit=false;window.EJS_color='#9be33a';window.EJS_backgroundColor='#050706';window.EJS_controlScheme='n64';window.EJS_defaultOptions={"save-state-location":"browser","mupen64plus-43screensize":"320x240","mupen64plus-aspect":"4:3","mupen64plus-MultiSampling":"0"};window.EJS_onGameStart=async()=>{const e=await wait();if(e){ready=true;enable(true);stat('Running locally in your browser.');cstat('Nintendo 64 controls ready.','good');window.dispatchEvent(new Event('pixelplayer:n64-ready'))}else cstat('The emulator started, but PixelPlayer could not connect to its control API.','warn')};const s=document.createElement('script');s.src='https://cdn.emulatorjs.org/stable/data/loader.js';s.async=true;s.onerror=()=>{stat('The Nintendo 64 emulator core could not be loaded.');cstat('Emulator runtime failed to load.','warn')};document.body.appendChild(s)}
window.startRom=startRom;input?.addEventListener('change',()=>{const f=input.files?.[0];input.value='';if(f)startRom(f)});['dragenter','dragover'].forEach(t=>drop?.addEventListener(t,e=>{e.preventDefault();drop.classList.add('dragging')}));['dragleave','drop'].forEach(t=>drop?.addEventListener(t,e=>{e.preventDefault();drop.classList.remove('dragging')}));drop?.addEventListener('drop',e=>{const f=e.dataTransfer?.files?.[0];if(f)startRom(f)});$('chooseAnotherBtn')?.addEventListener('click',()=>location.reload());$('enterPortraitBtn')?.addEventListener('click',()=>{if(ready){document.body.classList.add('rom-playing');scrollTo(0,0);dispatchEvent(new Event('resize'))}});$('playExitBtn')?.addEventListener('click',()=>{document.body.classList.remove('rom-playing');dispatchEvent(new Event('resize'))});
function toggleFF(){const e=emu();if(!ready||!e?.gameManager)return;ff=!ff;e.gameManager.setFastForwardRatio?.(3);e.gameManager.toggleFastForward?.(ff);$('fastForwardBtn').querySelector('span').textContent=ff?'⏩ Fast Forward ON':'⏩ Fast Forward: OFF';$('playFastForwardBtn').textContent=ff?'⏩ FF: ON':'⏩ FF: OFF';cstat(ff?'Fast forward enabled at 3× speed.':'Fast forward disabled.','good')}$('fastForwardBtn')?.addEventListener('click',toggleFF);$('playFastForwardBtn')?.addEventListener('click',toggleFF);
$('pauseBtn')?.addEventListener('click',()=>{const e=emu();if(!ready||!e)return;paused=!paused;if(paused)(typeof e.pause==='function'?e.pause():e.gameManager?.toggleMainLoop?.(0));else(typeof e.play==='function'?e.play():e.gameManager?.toggleMainLoop?.(1));$('pauseBtn').querySelector('span').textContent=paused?'▶ Resume':'⏸ Pause';cstat(paused?'Emulation paused.':'Emulation resumed.',paused?'info':'good')});$('resetBtn')?.addEventListener('click',()=>{try{emu()?.gameManager?.restart();paused=false;ff=false;cstat('Nintendo 64 reset.','good')}catch{cstat('Reset failed.','warn')}});$('fullscreenBtn')?.addEventListener('click',async()=>{try{const e=emu();if(typeof e?.toggleFullscreen==='function')e.toggleFullscreen(!document.fullscreenElement);else if(!document.fullscreenElement)await stage.requestFullscreen();else await document.exitFullscreen()}catch{cstat('Fullscreen could not be changed.','warn')}});$('screenshotBtn')?.addEventListener('click',async()=>{try{const d=await emu()?.gameManager?.screenshot();if(d)download(d,`${current}_screenshot.png`,'image/png')}catch{cstat('Screenshot failed.','warn')}});
$('exportSaveBtn')?.addEventListener('click',()=>{try{const gm=emu()?.gameManager,save=gm?.getSaveFile?.();if(!save||!save.length){cstat('No cartridge save is available yet.','warn');return}download(save,`${current}.sav`);cstat(`Exported ${current}.sav.`,'good')}catch{cstat('Could not export the cartridge save.','warn')}});
$('saveInput')?.addEventListener('change',async()=>{const f=$('saveInput').files?.[0];$('saveInput').value='';const gm=emu()?.gameManager;if(!f||!ready||!gm)return;try{const bytes=new Uint8Array(await f.arrayBuffer()),path=gm.getSaveFilePath?.();if(!path)throw 0;gm.writeFile(path,bytes);gm.loadSaveFiles?.();gm.FS?.syncfs?.(false,()=>{});cstat(`Imported ${f.name}. Reset if needed.`,'good')}catch{cstat('Could not import that save file.','warn')}});
function pad(){const p=[...(navigator.getGamepads?.()||[])].find(Boolean);if($('controllerStatus'))$('controllerStatus').textContent=p?(p.id||'Controller').slice(0,65):'No controller detected';if($('mappingSummary')){$('mappingSummary').className=p?'mapping-summary':'mapping-summary empty-state';$('mappingSummary').textContent=p?'N64 gamepad mapping active: analog stick, A/B, Start, triggers, D-pad and C buttons.':'Waiting for controller input…'}}
window.addEventListener('gamepadconnected',pad);window.addEventListener('gamepaddisconnected',pad);document.querySelector('[data-tab="controller"]')?.addEventListener('click',pad);pad();enable(false);
})();