// Build 63: shared navigation with Home, Palette Tool, and hard emulator handoff.
(()=>{
  if(!document.querySelector('link[href*="nav.css"]')){const css=document.createElement('link');css.rel='stylesheet';css.href='nav.css?v=47';document.head.appendChild(css)}
  const nav=document.querySelector('.tool-tabs');if(!nav)return;const page=(location.pathname.split('/').pop()||'index.html').toLowerCase();
  const systems=[['3do.html','3DO'],['amiga.html','Amiga'],['amstrad.html','Amstrad CPC'],['arcade.html','Arcade / FBNeo'],['atari.html','Atari 2600'],['atari5200.html','Atari 5200'],['atari7800.html','Atari 7800'],['jaguar.html','Atari Jaguar'],['lynx.html','Atari Lynx'],['cdi.html','Philips CD-i'],['coleco.html','ColecoVision'],['commodore.html','Commodore / VICE'],['doom.html','Doom / PrBoom'],['emulator.html','GBA'],['gamegear.html','Game Gear'],['gbc.html','Game Boy / Color'],['genesis.html','Genesis / Mega Drive'],['mame.html','MAME 2003'],['mastersystem.html','Master System'],['ngp.html','Neo Geo Pocket'],['nes.html','NES / Famicom'],['n64.html','Nintendo 64'],['nds.html','Nintendo DS'],['ps1.html','PlayStation'],['psp.html','PSP'],['sega32x.html','Sega 32X'],['segacd.html','Sega CD'],['saturn.html','Sega Saturn'],['snes.html','SNES'],['turbografx.html','TurboGrafx / PC Engine'],['virtualboy.html','Virtual Boy'],['wonderswan.html','WonderSwan'],['zx81.html','ZX81'],['zxspectrum.html','ZX Spectrum']].sort((a,b)=>a[1].localeCompare(b[1],undefined,{numeric:true,sensitivity:'base'}));
  const active=systems.find(([href])=>page===href);nav.innerHTML='';
  function go(href){if(window.PixelPlayerSession?.hardNavigate)window.PixelPlayerSession.hardNavigate(href);else location.assign(href)}
  function link(href,label,activeNow=false,extra=''){const a=document.createElement('a');a.className=`tool-tab ${extra}${activeNow?' active':''}`.trim();a.href=href;a.innerHTML=`<span class="tab-dot"></span>${label}`;a.addEventListener('click',e=>{if(page===href)return;e.preventDefault();go(href)});return a}
  nav.appendChild(link('index.html','Home',page==='index.html'||page==='','nav-home'));
  nav.appendChild(link('palette.html','Palette Tool',page==='palette.html','nav-palette'));
  const wrap=document.createElement('div');wrap.className=`emulator-dropdown${active?' active':''}`;const button=document.createElement('button');button.type='button';button.className='tool-tab emulator-dropdown-toggle';button.setAttribute('aria-haspopup','menu');button.setAttribute('aria-expanded','false');button.innerHTML=`<span class="tab-dot"></span><span>${active?active[1]:'Emulators'}</span><b aria-hidden="true">▾</b>`;
  const menu=document.createElement('div');menu.className='emulator-dropdown-menu';menu.setAttribute('role','menu');systems.forEach(([href,label])=>{const a=document.createElement('a');a.href=href;a.className=`emulator-dropdown-item${page===href?' active':''}`;a.setAttribute('role','menuitem');a.innerHTML=`<span class="tab-dot"></span>${label}`;a.addEventListener('click',e=>{if(page===href)return;e.preventDefault();setOpen(false);go(href)});menu.appendChild(a)});wrap.append(button,menu);nav.appendChild(wrap);
  const style=document.createElement('style');style.textContent='.emulator-dropdown-menu{max-height:min(74vh,620px);overflow-y:auto;overscroll-behavior:contain}.emulator-dropdown-menu::-webkit-scrollbar{width:7px}.emulator-dropdown-menu::-webkit-scrollbar-thumb{background:#344039;border-radius:99px}';document.head.appendChild(style);
  function setOpen(open){wrap.classList.toggle('open',open);button.setAttribute('aria-expanded',open?'true':'false')}button.addEventListener('click',e=>{e.stopPropagation();setOpen(!wrap.classList.contains('open'))});document.addEventListener('click',e=>{if(!wrap.contains(e.target))setOpen(false)});document.addEventListener('keydown',e=>{if(e.key==='Escape'){setOpen(false);button.focus()}});
})();