// Build 47: shared compact navigation for the full emulator family.
(()=>{
  if(!document.querySelector('link[href*="nav.css"]')){const css=document.createElement('link');css.rel='stylesheet';css.href='nav.css?v=47';document.head.appendChild(css)}
  const nav=document.querySelector('.tool-tabs');if(!nav)return;const page=(location.pathname.split('/').pop()||'index.html').toLowerCase();
  const systems=[['emulator.html','GBA'],['gbc.html','Game Boy / Color'],['nes.html','NES / Famicom'],['snes.html','SNES'],['n64.html','Nintendo 64'],['nds.html','Nintendo DS'],['virtualboy.html','Virtual Boy'],['ps1.html','PlayStation'],['psp.html','PSP'],['genesis.html','Genesis / Mega Drive'],['gamegear.html','Game Gear'],['mastersystem.html','Master System'],['segacd.html','Sega CD'],['sega32x.html','Sega 32X'],['saturn.html','Sega Saturn'],['atari.html','Atari 2600'],['atari5200.html','Atari 5200'],['atari7800.html','Atari 7800'],['jaguar.html','Atari Jaguar'],['lynx.html','Atari Lynx'],['3do.html','3DO'],['arcade.html','Arcade / FBNeo'],['mame.html','MAME 2003'],['turbografx.html','TurboGrafx / PC Engine'],['ngp.html','Neo Geo Pocket'],['wonderswan.html','WonderSwan'],['coleco.html','ColecoVision'],['commodore.html','Commodore / VICE'],['amiga.html','Amiga'],['zxspectrum.html','ZX Spectrum'],['zx81.html','ZX81'],['amstrad.html','Amstrad CPC'],['doom.html','Doom / PrBoom'],['cdi.html','Philips CD-i']];
  const active=systems.find(([href])=>page===href);nav.innerHTML='';const palette=document.createElement('a');palette.className=`tool-tab nav-palette${page==='index.html'||page===''?' active':''}`;palette.href='index.html';palette.innerHTML='<span class="tab-dot"></span>Palette Tool';nav.appendChild(palette);
  const wrap=document.createElement('div');wrap.className=`emulator-dropdown${active?' active':''}`;const button=document.createElement('button');button.type='button';button.className='tool-tab emulator-dropdown-toggle';button.setAttribute('aria-haspopup','menu');button.setAttribute('aria-expanded','false');button.innerHTML=`<span class="tab-dot"></span><span>${active?active[1]:'Emulators'}</span><b aria-hidden="true">▾</b>`;
  const menu=document.createElement('div');menu.className='emulator-dropdown-menu';menu.setAttribute('role','menu');systems.forEach(([href,label])=>{const a=document.createElement('a');a.href=href;a.className=`emulator-dropdown-item${page===href?' active':''}`;a.setAttribute('role','menuitem');a.innerHTML=`<span class="tab-dot"></span>${label}`;menu.appendChild(a)});wrap.append(button,menu);nav.appendChild(wrap);
  const style=document.createElement('style');style.textContent='.emulator-dropdown-menu{max-height:min(74vh,620px);overflow-y:auto;overscroll-behavior:contain}.emulator-dropdown-menu::-webkit-scrollbar{width:7px}.emulator-dropdown-menu::-webkit-scrollbar-thumb{background:#344039;border-radius:99px}';document.head.appendChild(style);
  function setOpen(open){wrap.classList.toggle('open',open);button.setAttribute('aria-expanded',open?'true':'false')}button.addEventListener('click',e=>{e.stopPropagation();setOpen(!wrap.classList.contains('open'))});document.addEventListener('click',e=>{if(!wrap.contains(e.target))setOpen(false)});document.addEventListener('keydown',e=>{if(e.key==='Escape'){setOpen(false);button.focus()}});
})();