// Build 62: PS1 manual save states with event-driven IndexedDB refresh.
(()=>{
  const slots=[...document.querySelectorAll('.ps1-state-slot')];
  const status=document.getElementById('ps1SaveStatus');
  const stage=document.getElementById('emuStage');
  if(!slots.length)return;
  const DB_NAME='PixelPlayerPs1States',STORE='states';let busy=false;const objectUrls=new Map();
  function setStatus(message,kind='info'){if(!status)return;status.textContent=message;status.className=`status ${kind}`}
  function getGameManager(){return window.EJS_emulator?.gameManager||null}
  function isReady(){return !!(stage?.classList.contains('ready')&&getGameManager())}
  function gameName(){const raw=(document.getElementById('sessionRom')?.textContent||'ps1-game').trim();return raw&&raw!=='No game loaded'?raw:'ps1-game'}
  function key(slot){return `${gameName()}::slot-${slot}`}
  function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'key'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
  async function getStateRow(slot){try{const db=await openDb();const row=await new Promise((resolve,reject)=>{const req=db.transaction(STORE,'readonly').objectStore(STORE).get(key(slot));req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error)});db.close();return row}catch{return null}}
  async function captureScreenshot(gm){try{if(typeof gm?.screenshot!=='function')return null;const bytes=await gm.screenshot();if(!bytes||!bytes.length)return null;return new Blob([bytes],{type:'image/png'})}catch(error){console.warn('PS1 save-state thumbnail failed',error);return null}}
  async function putState(slot,bytes,thumbnail){const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put({key:key(slot),game:gameName(),slot:Number(slot),savedAt:Date.now(),blob:new Blob([bytes],{type:'application/octet-stream'}),thumbnail:thumbnail||null});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}
  function renderThumb(card,row,slot){const thumb=card.querySelector('.state-thumb');if(!thumb)return;const old=objectUrls.get(slot);if(old){URL.revokeObjectURL(old);objectUrls.delete(slot)}if(row?.thumbnail instanceof Blob&&row.thumbnail.size){const url=URL.createObjectURL(row.thumbnail);objectUrls.set(slot,url);thumb.className='state-thumb';thumb.innerHTML='';const img=document.createElement('img');img.src=url;img.alt=`Slot ${slot} screenshot`;thumb.appendChild(img)}else{thumb.className='state-thumb empty';thumb.innerHTML=`<span>Slot ${slot}</span>`}}
  async function render(){const ready=isReady();for(const card of slots){const slot=card.dataset.slot,row=await getStateRow(slot),time=card.querySelector('.state-time'),save=card.querySelector('.save-state-btn'),load=card.querySelector('.load-state-btn');renderThumb(card,row,slot);if(time)time.textContent=row?.savedAt?new Date(row.savedAt).toLocaleString():'Empty';if(save)save.disabled=!ready||busy;if(load)load.disabled=!ready||busy||!row}if(!ready)setStatus('Start a PlayStation game to enable manual save states.')}
  async function saveSlot(slot){if(busy||!isReady())return;const gm=getGameManager();if(typeof gm?.getState!=='function'){setStatus('This PlayStation core does not expose manual save states.','warn');return}busy=true;await render();setStatus(`Saving Slot ${slot}…`);try{const state=gm.getState();if(!state||!state.length)throw new Error('No state data returned');const thumbnail=await captureScreenshot(gm);await putState(slot,state,thumbnail);setStatus(thumbnail?`Saved Slot ${slot} with screenshot.`:`Saved Slot ${slot}. Screenshot unavailable for this frame.`,'good')}catch(error){console.warn('PS1 save-state failed',error);setStatus('Could not save that state. Browser storage may be full.','warn')}finally{busy=false;await render();window.dispatchEvent(new CustomEvent('pixelplayer:manual-state-saved',{detail:{slot:+slot,system:'ps1'}}))}}
  async function loadSlot(slot){if(busy||!isReady())return;const gm=getGameManager();if(typeof gm?.loadState!=='function'){setStatus('This PlayStation core does not expose manual save states.','warn');return}busy=true;await render();setStatus(`Loading Slot ${slot}…`);try{const row=await getStateRow(slot);if(!row?.blob){setStatus(`Slot ${slot} is empty.`,'warn');return}const bytes=new Uint8Array(await row.blob.arrayBuffer());gm.loadState(bytes);setStatus(`Loaded Slot ${slot}.`,'good')}catch(error){console.warn('PS1 load-state failed',error);setStatus('Could not load that state.','warn')}finally{busy=false;await render();window.dispatchEvent(new CustomEvent('pixelplayer:manual-state-loaded',{detail:{slot:+slot,system:'ps1'}}))}}
  slots.forEach(card=>{const slot=card.dataset.slot;card.querySelector('.save-state-btn')?.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();saveSlot(slot)});card.querySelector('.load-state-btn')?.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();loadSlot(slot)})});
  const observer=new MutationObserver(()=>render());if(stage)observer.observe(stage,{attributes:true,attributeFilter:['class']});window.addEventListener('pixelplayer:ps1-ready',render);document.querySelector('[data-tab="saves"]')?.addEventListener('click',render);
  const cleanup=()=>{for(const url of objectUrls.values())URL.revokeObjectURL(url);objectUrls.clear()};window.addEventListener('beforeunload',cleanup);window.addEventListener('pixelplayer:hard-unload',cleanup);render();
})();