// Build 84: compact shared PixelPlayer page shell for expanded systems.
(()=>{
 const b=document.body,d=b.dataset,label=d.label||d.system,coreLabel=d.coreLabel||d.core,ext=d.ext||'';
 const bios=d.biosRequired==='true'?`<div class="tab-card"><div class="card-heading"><h2>${label} BIOS</h2><span>Required</span></div><label class="save-import secondary" style="display:inline-flex">Choose BIOS<input id="biosInput" type="file" accept=".bin,.rom,.bios,application/octet-stream" hidden></label><p class="section-note">Use your own legally obtained BIOS. It stays local to this browser session.</p></div>`:'';
 const slots=[1,2,3].map(n=>`<article class="state-slot generic-state-slot" data-slot="${n}"><div class="state-thumb empty"><span>Slot ${n}</span></div><div class="state-meta"><strong>Slot ${n}</strong><span class="state-time">Empty</span></div><div class="state-actions"><button class="secondary save-state-btn" disabled>Save</button><button class="secondary load-state-btn" disabled>Load</button></div></article>`).join('');
 b.innerHTML=`<div class="ambient ambient-a"></div><div class="ambient ambient-b"></div><main class="emulator-shell"><nav class="tool-tabs" aria-label="PixelPlayer navigation"></nav>
 <section id="emuStage" class="panel emulator-stage"><div class="section-kicker">EMULATOR</div><div class="screen-frame"><div id="game"></div></div><div class="play-overlay-controls" aria-label="Play mode controls"><button id="playFastForwardBtn" class="play-control" type="button">⏩ FF: OFF</button><button id="playExitBtn" class="play-control" type="button">☰ Menu</button></div><div class="stage-actions"><span id="emuStatus" class="emu-status">Select a game to start.</span><div class="stage-action-buttons"><button id="enterPortraitBtn" class="primary" type="button">Vertical Full Screen</button><button id="chooseAnotherBtn" class="secondary" type="button">Load Different Game</button></div></div></section>
 <section class="panel emulator-workbench" aria-label="${label} emulator controls"><div class="emulator-subtabs" role="tablist"><button class="emulator-subtab" type="button" role="tab" data-tab="play">Play</button><button class="emulator-subtab active" type="button" role="tab" data-tab="roms">Games</button><button class="emulator-subtab" type="button" role="tab" data-tab="saves">Saves</button><button class="emulator-subtab" type="button" role="tab" data-tab="controller">Controller</button><button class="emulator-subtab" type="button" role="tab" data-tab="info">Info</button></div><div class="emulator-tab-panels">
 <section class="emulator-tab-panel" data-panel="play" hidden><div id="controlCenter" class="tab-card control-center disabled-panel"><div class="card-heading"><h2>Game Session</h2><span id="sessionRom">No game loaded</span></div><div class="control-grid"><button id="pauseBtn" class="secondary" disabled><span>⏸ Pause</span><small>Freeze emulation</small></button><button id="fastForwardBtn" class="secondary" disabled><span>⏩ Fast Forward: OFF</span><small>Toggle 3×</small></button><button id="resetBtn" class="secondary" disabled><span>↻ Reset</span><small>Restart system</small></button><button id="fullscreenBtn" class="secondary" disabled><span>⛶ Fullscreen</span><small>Expand emulator</small></button><button id="screenshotBtn" class="secondary" disabled><span>▣ Screenshot</span><small>Download PNG</small></button></div><div id="controlStatus" class="status info">Controls become available after the emulator starts.</div></div></section>
 <section class="emulator-tab-panel active" data-panel="roms"><div class="tab-card rom-loader compact-loader"><div class="card-heading"><h2>Open ${label} Game</h2><span id="romName">No game selected</span></div><label id="romDrop" class="rom-drop compact-drop" for="romInput"><input id="romInput" type="file" accept="${d.accept||'application/octet-stream'}" hidden><div class="upload-icon">▶</div><span class="rom-title">Choose a ${label} game</span><span class="rom-subtitle">Tap here or drop a supported ROM, ZIP, or 7z file.</span></label><div class="rom-meta"><span>ZIP/7z extraction handled locally</span><span>Files stay on this device</span></div></div>${bios}
 <div id="romLibraryPanel" class="tab-card rom-library-panel"><div class="card-heading"><h2>Folder Library</h2><span id="romLibraryCount">0 Games</span></div><input id="romFolderInput" type="file" accept="${d.accept||'application/octet-stream'}" webkitdirectory directory multiple hidden><div class="rom-library-toolbar"><button id="chooseRomFolderBtn" class="primary" type="button">📁 Choose Game Folder</button><button id="clearRomLibraryBtn" class="secondary" type="button">Clear Library</button><input id="romLibrarySearch" class="rom-library-search" type="search" placeholder="Search games or folders…"></div><div class="rom-library-summary"><span id="romLibraryStatus">No game folder scanned yet.</span><span>Subfolders included</span></div><div id="romLibraryList" class="rom-library-list empty-state">Choose a folder to build your library.</div></div>
 <div id="recentRomsPanel" class="tab-card recent-roms-panel"><div class="card-heading"><h2>Recently Played</h2><button id="clearRecentRomsBtn" class="secondary" type="button">Clear</button></div><div id="recentRoms" class="recent-roms empty-state">No recent games yet.</div></div></section>
 <section class="emulator-tab-panel" data-panel="saves" hidden><div class="tab-card save-center"><div class="save-copy"><strong>Cartridge / Memory Save</strong><span>Import or export the running core's save-memory file when supported.</span></div><div class="save-actions"><button id="exportSaveBtn" class="secondary" disabled>Export Save</button><label class="secondary save-import disabled" id="importSaveLabel">Import Save<input id="saveInput" type="file" accept=".sav,.srm,.eep,.fla,.dat,application/octet-stream" hidden disabled></label></div></div><div class="tab-card state-section"><div class="state-heading"><div><strong>Manual Save States</strong><span>Three local slots per game. Switching tabs does not recreate the emulator.</span></div><small>Stored in IndexedDB</small></div><div class="state-slots">${slots}</div></div></section>
 <section class="emulator-tab-panel" data-panel="controller" hidden><div class="tab-card controller-panel"><div class="card-heading"><h2>Controller</h2><span id="controllerStatus">No controller detected</span></div><p class="section-note">Connect a standard gamepad and press a button so the browser can detect it. EmulatorJS handles the system mapping.</p><div class="mapping-summary empty-state">Waiting for controller input…</div></div></section>
 <section class="emulator-tab-panel" data-panel="info" hidden><div class="tab-card"><div class="info-grid"><div><strong>Supported files</strong><span>${ext}</span></div><div><strong>Default core</strong><span>${coreLabel}</span></div><div><strong>Archives</strong><span>EmulatorJS can decompress ZIP/7z for normal games; arcade ROM sets are kept intact when required by the core.</span></div></div></div><div class="tab-card orange-accent"><div class="section-kicker">ABOUT THE CORE</div><p class="license-note">This page integrates EmulatorJS. No ROMs, games, or copyrighted firmware are included with PixelPlayer. Use files you are legally permitted to use.</p></div></section>
 </div></section><footer>PixelPlayer · browser-based multi-system emulation</footer></main>`;
 function inject(src,v){if(document.querySelector(`script[src*="${src}"]`))return;const s=document.createElement('script');s.src=`${src}?v=${v}`;s.defer=true;document.body.appendChild(s)}
 inject('emulator-session.js',84);inject('controller-themes.js',48);inject('control-layout.js',51);inject('quick-resume.js',53);inject('overlay-state-menu.js',62);
})();